/**
 * Main-process AI agent: owns the Anthropic client, per-chat conversation
 * history, and the streaming tool-use loop. The renderer talks to it through
 * `agent:*` IPC handles and receives progress as `agent:event` pushes.
 *
 * Execution safety model: the user picks an access mode per chat. Metadata
 * Only offers no execution tools at all; Read-Only routes every statement
 * through runAgentQuery — the guarded channel that admits exactly one
 * provably-read statement per call, with the server-side read-only session
 * as a second belt. There is no approval flow: statements that modify data
 * or schema are blocked outright, in every mode.
 *
 * Implementation is split across src/main/agent/*: prompt.ts (system-prompt
 * assembly), knowledge.ts (local-knowledge rendering, search, and its two
 * tool executors), tools.ts (static tool definitions), and executors.ts (the
 * remaining tool executors). This file re-exports their public surface so
 * existing imports of './agent' keep working, and keeps the per-chat state,
 * the schema cache, the turn loop, /compact, and IPC registration.
 */

import Anthropic from '@anthropic-ai/sdk'
import type { BrowserWindow } from 'electron'

import { typedHandle, typedOn, typedSend } from './ipc'
import { agentCapabilityFor, getConnectionType, introspectDatabase } from './db'
import type {
  AgentCompactResult,
  AgentEditorReadPayload,
  AgentKeyStatus,
  AgentSendRequest,
  AgentTargetRef
} from '../shared/agent'
import { AGENT_MODELS, clampAgentMode, resolveAgentMode } from '../shared/agent'
import { apiKeyVarName, loadApiKey } from './settings'
import { mcpToolsForTurn } from './mcp'
import type { McpAgentTool } from './mcp'
import { getRepoCommit, getRepoRoot } from './repo'
import { targetsForBase } from './knowledge'
import { normalizeColumnKey, tableNameAliases } from '../shared/knowledge'
import type { KnowledgeChangeEvent } from '../shared/knowledge'
import type { DatabaseIntrospection } from '../shared/db'
import { dialectFor } from '../shared/dialect'

import { buildSystemPrompt, summarizeSchema } from './agent/prompt'
import type { RepoPromptInfo } from './agent/prompt'
import {
  execSearchKnowledge,
  execSaveKnowledge,
  resolveActiveKbId,
  setBroadcastKnowledgeChanged
} from './agent/knowledge'
import {
  LIST_REPO_FILES_TOOL,
  GREP_REPO_TOOL,
  READ_EDITOR_TOOL,
  READ_REPO_FILE_TOOL,
  SAVE_KNOWLEDGE_TOOL,
  SEARCH_KNOWLEDGE_TOOL,
  WRITE_EDITOR_TOOL,
  describeTableTool,
  explainQueryTool,
  runSqlTool,
  searchSchemaTool,
  webSearchTool
} from './agent/tools'
import {
  describeError,
  execDescribeTable,
  execExplain,
  execGrepRepo,
  execListRepoFiles,
  execMcpTool,
  execReadEditor,
  execReadRepoFile,
  execRunSql,
  execSearchSchema,
  execWriteEditor,
  setReadEditorFromRenderer,
  EDITOR_READ_TIMEOUT_MS
} from './agent/executors'
import type { Sender } from './agent/executors'

export * from './agent/prompt'
export * from './agent/knowledge'
export * from './agent/tools'
export * from './agent/executors'

export interface ChatState {
  messages: Anthropic.MessageParam[]
  controller: AbortController | null
  /** Cancels the agent's currently running statement, when one is running. */
  cancelRunningQuery: (() => void) | null
  /**
   * Server-side code-execution container reported by the API when the
   * dynamic-filtering web search tool runs. Follow-up requests must echo its
   * id while the conversation has pending code-exec tool uses, or the API
   * rejects them ("container_id is required when there are pending tool
   * uses generated by code execution with tools").
   */
  container: { id: string; expiresAt: string } | null
}

const chats = new Map<string, ChatState>()

function getChat(chatId: string): ChatState {
  let chat = chats.get(chatId)
  if (!chat) {
    chat = {
      messages: [],
      controller: null,
      cancelRunningQuery: null,
      container: null
    }
    chats.set(chatId, chat)
  }
  return chat
}

/** Schema summaries are reused across turns; introspection can be slow. */
const schemaCache = new Map<string, string>()

/**
 * The introspection behind each cached summary, kept for save_knowledge ref
 * checking. Same key space and lifecycle as schemaCache (both clear on
 * agent:reset), so the two can never describe different snapshots.
 */
const introspectionCache = new Map<string, DatabaseIntrospection>()

function schemaCacheKey(target: AgentTargetRef): string {
  return `${target.connId}/${target.database}`
}

/**
 * Drop cached schema summaries for a connection (one database, or all of
 * them when omitted). Called when the user changes a schema/catalog
 * selection so the agent's next turn reflects the new pinning without
 * waiting for agent:reset.
 */
export function invalidateAgentSchemaCache(connId: string, database?: string): void {
  const match = (key: string): boolean =>
    database !== undefined ? key === `${connId}/${database}` : key.startsWith(`${connId}/`)
  for (const cache of [schemaCache, introspectionCache]) {
    for (const key of [...cache.keys()]) {
      if (match(key)) cache.delete(key)
    }
  }
}

async function schemaSummaryFor(target: AgentTargetRef): Promise<string> {
  const cacheKey = schemaCacheKey(target)
  const cached = schemaCache.get(cacheKey)
  if (cached) return cached
  const res = await introspectDatabase(target.connId, target.database)
  if (!res.ok) return `(schema introspection failed: ${res.error})`
  const summary = summarizeSchema(res.data)
  schemaCache.set(cacheKey, summary)
  introspectionCache.set(cacheKey, res.data)
  return summary
}

/**
 * Every normalized ref key the live schema can satisfy — `schema.table` for
 * each relation plus `schema.table.column` for each column — or null when no
 * introspection has been cached for the target this session. Used to flag
 * (never block) save_knowledge records whose refs match nothing real. Each
 * relation also registers its `tableNameAliases`, matching the renderer's
 * buildRefKeySet, so refs authored against the other engine's naming
 * convention (schema-prefixed Databricks tables) aren't reported unresolved.
 */
export function liveRefKeys(target: AgentTargetRef): Set<string> | null {
  const db = introspectionCache.get(schemaCacheKey(target))
  if (!db) return null
  const keys = new Set<string>()
  for (const schema of db.schemas) {
    for (const rel of [...schema.tables, ...schema.views, ...schema.matviews]) {
      for (const table of [rel.name, ...tableNameAliases(schema.name, rel.name)]) {
        keys.add(normalizeColumnKey({ schema: schema.name, table }))
        for (const col of rel.columns) {
          keys.add(
            normalizeColumnKey({
              schema: schema.name,
              table,
              column: col.name
            })
          )
        }
      }
    }
  }
  return keys
}

/**
 * Move the incremental cache breakpoint to the last (user) message so each
 * request reuses the previous request's cached prefix instead of paying for
 * the whole conversation again on every tool round-trip.
 */
function setCacheBreakpoint(messages: Anthropic.MessageParam[]): void {
  for (const msg of messages) {
    if (Array.isArray(msg.content)) {
      for (const blk of msg.content) {
        delete (blk as { cache_control?: unknown }).cache_control
      }
    }
  }
  const last = messages[messages.length - 1]
  if (!last) return
  if (typeof last.content === 'string') {
    last.content = [{ type: 'text', text: last.content }]
  }
  const tail = last.content[last.content.length - 1]
  if (tail) {
    ;(tail as { cache_control?: unknown }).cache_control = { type: 'ephemeral' }
  }
}

/**
 * An errored or aborted turn can leave the history ending in an assistant
 * message with unanswered tool_use blocks, which the API rejects on every
 * later request — the chat would be wedged for good. Pair each dangling
 * tool_use with a synthetic error result before starting the next turn.
 */
function repairDanglingToolUses(messages: Anthropic.MessageParam[]): void {
  const last = messages[messages.length - 1]
  if (!last || last.role !== 'assistant' || !Array.isArray(last.content)) return
  const results: Anthropic.ToolResultBlockParam[] = []
  for (const blk of last.content) {
    if (blk.type === 'tool_use') {
      results.push({
        type: 'tool_result',
        tool_use_id: blk.id,
        content: 'Interrupted before the tool ran.',
        is_error: true
      })
    }
  }
  if (results.length > 0) messages.push({ role: 'user', content: results })
}

/** Whether a completed model response still owes a promised editor diff. */
export function shouldForceEditorProposal(
  req: Pick<AgentSendRequest, 'intent'>,
  stopReason: string | null,
  editorProposalSent: boolean,
  reminderSent: boolean
): boolean {
  return (
    req.intent === 'fix-query' && !editorProposalSent && !reminderSent && stopReason === 'end_turn'
  )
}

async function runAgentTurn(req: AgentSendRequest, send: Sender): Promise<void> {
  const { key } = loadApiKey()
  if (!key) {
    send({
      type: 'error',
      chatId: req.chatId,
      message: `No API key found. Add one in Settings, or add \`export ${apiKeyVarName()}=...\` to ~/.zshrc and try again.`
    })
    return
  }
  const model = AGENT_MODELS.find((m) => m.id === req.model) ?? AGENT_MODELS[0]
  const chat = getChat(req.chatId)
  if (chat.controller) {
    send({
      type: 'error',
      chatId: req.chatId,
      message: 'A response is already in progress.'
    })
    return
  }
  const controller = new AbortController()
  chat.controller = controller

  // Fail closed: a renderer bug or tampering that sends 'write-admin' or
  // garbage silently degrades to Metadata Only. The same applies to
  // 'read-only' on a connection whose capability (decided in the facade at
  // connect time) clamps the agent — prod with a role that can write, or one
  // that couldn't be verified. The clamp happens before the system prompt
  // and tool array are built, so a clamped turn is indistinguishable from a
  // Metadata Only one.
  const capability = req.target ? agentCapabilityFor(req.target.connId) : null
  const mode = clampAgentMode(resolveAgentMode(req.mode), capability)
  const client = new Anthropic({ apiKey: key })
  // Dialect follows the target connection's engine; chats without a target
  // default to PostgreSQL guidance.
  const dialect = dialectFor(req.target ? getConnectionType(req.target.connId) : null)
  const schemaSummary = req.target ? await schemaSummaryFor(req.target) : null
  // MCP tools are user-configured and mode-independent: the access mode
  // protects the connected database, while MCP servers act on external
  // systems with their own credentials. Snapshot once per turn so the tool
  // array and the dispatch below cannot disagree mid-turn.
  const mcpTools = mcpToolsForTurn()
  const mcpByName = new Map(mcpTools.map((t) => [t.namespacedName, t]))
  // Repo access requires both halves: the renderer's per-chat toggle AND a
  // main-side configured root on the turn's active knowledge base. The
  // request never carries a path, so a tampered renderer can at most toggle
  // access to a directory the user already attached through the main-process
  // picker, on a base actually linked to the target.
  const activeKbId = req.target ? resolveActiveKbId(req.target) : null
  const repoRoot = req.repo && activeKbId ? getRepoRoot(activeKbId) : null
  const repo: RepoPromptInfo | null = repoRoot
    ? { root: repoRoot, commit: await getRepoCommit(repoRoot) }
    : null
  // The system prompt (with the schema summary) is by far the largest stable
  // prefix; cache it so follow-up turns and tool round-trips reuse it.
  const system: Anthropic.TextBlockParam[] = [
    {
      type: 'text',
      text: buildSystemPrompt(req, mode, schemaSummary, dialect, mcpTools, repo),
      cache_control: { type: 'ephemeral' }
    }
  ]
  // Metadata Only offers no execution tools at all (Layer 1); its schema
  // knowledge is the system-prompt summary above.
  const tools: Anthropic.Messages.ToolUnion[] =
    req.target && mode === 'read-only'
      ? [
          WRITE_EDITOR_TOOL,
          READ_EDITOR_TOOL,
          runSqlTool(dialect),
          explainQueryTool(dialect),
          describeTableTool(dialect),
          searchSchemaTool(dialect)
        ]
      : [WRITE_EDITOR_TOOL, READ_EDITOR_TOOL]
  // search_knowledge and save_knowledge read/write only the local knowledge
  // store — never the warehouse — so both are offered in Metadata Only as well
  // as Read-Only. They require a target because records are keyed to it.
  if (req.target) tools.push(SEARCH_KNOWLEDGE_TOOL, SAVE_KNOWLEDGE_TOOL)
  // Repo tools read only the attached local checkout — never the database —
  // so, like the knowledge tools, they are mode-independent.
  if (repoRoot) {
    tools.push(LIST_REPO_FILES_TOOL, GREP_REPO_TOOL, READ_REPO_FILE_TOOL)
  }
  for (const t of mcpTools) {
    tools.push({
      name: t.namespacedName,
      description: `Tool "${t.toolName}" from the user-configured MCP server "${t.serverName}".${t.description ? ` ${t.description}` : ''}`,
      input_schema: t.inputSchema as Anthropic.Tool.InputSchema
    })
  }
  // Web search runs server-side; results come back as content blocks, so
  // there is no execution branch in the tool-use loop below.
  const webTool = req.webSearch ? webSearchTool(model.id) : null
  if (webTool) tools.push(webTool)
  // The dynamic-filtering variant runs code execution in a server-side
  // container; its id must be echoed back on requests that continue the
  // conversation, and it may only be sent when the tool is in the request.
  const canSendContainer = webTool?.type === 'web_search_20260209'

  repairDanglingToolUses(chat.messages)
  chat.messages.push({ role: 'user', content: req.prompt })

  // Latest known context occupancy, updated after every API call so the
  // renderer's gauge stays accurate even when the turn aborts mid-loop.
  let contextTokens: number | null = null
  let editorProposalSent = false
  let forceEditorProposal = false
  let editorProposalReminderSent = false

  try {
    for (;;) {
      setCacheBreakpoint(chat.messages)
      // Reuse the live container, dropping it shortly before it expires so a
      // stale id doesn't fail the request.
      const containerId =
        canSendContainer &&
        chat.container &&
        Date.parse(chat.container.expiresAt) - Date.now() > 30_000
          ? chat.container.id
          : null
      const stream = client.messages.stream(
        {
          model: model.id,
          max_tokens: 64_000,
          ...(containerId ? { container: containerId } : {}),
          ...(model.adaptiveThinking && !forceEditorProposal
            ? { thinking: { type: 'adaptive' } }
            : {}),
          ...(req.effort && model.efforts.includes(req.effort)
            ? { output_config: { effort: req.effort } }
            : {}),
          system,
          tools,
          ...(forceEditorProposal
            ? {
                tool_choice: {
                  type: 'tool' as const,
                  name: 'write_to_editor',
                  disable_parallel_tool_use: true
                }
              }
            : {}),
          messages: chat.messages
        },
        { signal: controller.signal }
      )

      stream.on('text', (delta) => {
        send({ type: 'text_delta', chatId: req.chatId, text: delta })
      })
      stream.on('contentBlock', (block) => {
        if (block.type === 'thinking') {
          send({ type: 'thinking', chatId: req.chatId, active: false })
        }
        // Web search executes server-side mid-stream; mirror it into the
        // transcript the same way client tools are shown.
        if (block.type === 'server_tool_use' && block.name === 'web_search') {
          const query = String((block.input as { query?: unknown })?.query ?? '')
          send({
            type: 'tool_start',
            chatId: req.chatId,
            toolId: block.id,
            name: block.name,
            sql: `web search "${query}"`
          })
        }
        if (block.type === 'web_search_tool_result') {
          const content = block.content
          send(
            Array.isArray(content)
              ? {
                  type: 'tool_result',
                  chatId: req.chatId,
                  toolId: block.tool_use_id,
                  ok: true,
                  summary: `${content.length} result${content.length === 1 ? '' : 's'}`
                }
              : {
                  type: 'tool_result',
                  chatId: req.chatId,
                  toolId: block.tool_use_id,
                  ok: false,
                  summary: `search failed: ${content.error_code}`
                }
          )
        }
      })
      stream.on('streamEvent', (evt) => {
        if (evt.type === 'content_block_start' && evt.content_block.type === 'thinking') {
          send({ type: 'thinking', chatId: req.chatId, active: true })
        }
      })

      const message = await stream.finalMessage()
      const usage = message.usage
      contextTokens =
        usage.input_tokens +
        (usage.cache_read_input_tokens ?? 0) +
        (usage.cache_creation_input_tokens ?? 0) +
        usage.output_tokens
      chat.messages.push({ role: 'assistant', content: message.content })
      if (message.container) {
        chat.container = {
          id: message.container.id,
          expiresAt: message.container.expires_at
        }
      }

      if (message.stop_reason === 'pause_turn') continue

      if (message.stop_reason === 'tool_use') {
        const toolUses = message.content.filter(
          (b): b is Anthropic.ToolUseBlock => b.type === 'tool_use'
        )
        const results: Anthropic.ToolResultBlockParam[] = []
        for (const block of toolUses) {
          if (block.name === 'run_sql') {
            results.push(await execRunSql(req, chat, mode, block, send))
          } else if (block.name === 'explain_query') {
            results.push(await execExplain(req, chat, mode, block, send, dialect))
          } else if (block.name === 'describe_table') {
            results.push(await execDescribeTable(req, mode, block, send))
          } else if (block.name === 'search_schema') {
            results.push(await execSearchSchema(req, mode, block, send))
          } else if (block.name === 'search_knowledge') {
            results.push(execSearchKnowledge(req, block, send))
          } else if (block.name === 'save_knowledge') {
            results.push(execSaveKnowledge(req, block, send))
          } else if (block.name === 'write_to_editor') {
            const result = execWriteEditor(req, block, send)
            results.push(result)
            if (!result.is_error) editorProposalSent = true
          } else if (block.name === 'read_editor') {
            results.push(await execReadEditor(req, block, send))
          } else if (repoRoot && block.name === 'list_repo_files') {
            results.push(await execListRepoFiles(req, repoRoot, block, send))
          } else if (repoRoot && block.name === 'grep_repo') {
            results.push(await execGrepRepo(req, repoRoot, block, send))
          } else if (repoRoot && block.name === 'read_repo_file') {
            results.push(await execReadRepoFile(req, repoRoot, block, send))
          } else if (mcpByName.has(block.name)) {
            const tool = mcpByName.get(block.name) as McpAgentTool
            results.push(await execMcpTool(req, tool, block, send))
          } else {
            results.push({
              type: 'tool_result',
              tool_use_id: block.id,
              content: `Unknown tool: ${block.name}`,
              is_error: true
            })
          }
        }
        chat.messages.push({ role: 'user', content: results })
        forceEditorProposal = false
        continue
      }

      // A Fix with AI action promises an editor diff. Models can occasionally
      // answer with corrected SQL in prose despite the prompt, so give them one
      // constrained follow-up that must emit the editor proposal tool.
      if (
        shouldForceEditorProposal(
          req,
          message.stop_reason,
          editorProposalSent,
          editorProposalReminderSent
        )
      ) {
        editorProposalReminderSent = true
        forceEditorProposal = true
        chat.messages.push({
          role: 'user',
          content:
            'Apply the fix now: call write_to_editor with the complete corrected contents of the active SQL editor. Do not respond with explanation only.'
        })
        continue
      }

      send({
        type: 'done',
        chatId: req.chatId,
        stopReason: message.stop_reason,
        contextTokens
      })
      return
    }
  } catch (err) {
    if (err instanceof Anthropic.APIUserAbortError || controller.signal.aborted) {
      send({
        type: 'done',
        chatId: req.chatId,
        stopReason: 'aborted',
        contextTokens
      })
      return
    }
    send({ type: 'error', chatId: req.chatId, message: describeError(err) })
  } finally {
    chat.controller = null
  }
}

/** Cap on the summary a /compact call may produce. */
const COMPACT_MAX_TOKENS = 8192

const COMPACT_PROMPT = [
  'Summarize this conversation so the summary can replace the full history as context for future turns.',
  "Preserve, concisely: the user's goals and open questions; every schema fact learned (tables, columns, types, keys); key findings from queries that were run; the latest SQL under discussion, verbatim if it was final; and any constraints or preferences the user stated.",
  'Omit pleasantries and dead ends. Respond with the summary only.'
].join(' ')

/** Replace the chat history with a model-written summary of it (/compact). */
async function compactChat(chatId: string, modelId: string): Promise<AgentCompactResult> {
  const { key } = loadApiKey()
  if (!key) {
    return {
      ok: false,
      error: `No API key found. Add one in Settings, or add \`export ${apiKeyVarName()}=...\` to ~/.zshrc and try again.`
    }
  }
  const chat = chats.get(chatId)
  if (!chat || chat.messages.length === 0) {
    return { ok: false, error: 'Nothing to compact — the conversation is empty.' }
  }
  if (chat.controller) {
    return {
      ok: false,
      error: 'Wait for the current response to finish before compacting.'
    }
  }
  const model = AGENT_MODELS.find((m) => m.id === modelId) ?? AGENT_MODELS[0]
  const client = new Anthropic({ apiKey: key })

  // An aborted turn can leave dangling tool_use blocks; pair each with a
  // synthetic result or the API rejects the transcript.
  const content: Anthropic.ContentBlockParam[] = []
  const last = chat.messages[chat.messages.length - 1]
  if (last?.role === 'assistant' && Array.isArray(last.content)) {
    for (const blk of last.content) {
      if (blk.type === 'tool_use') {
        content.push({
          type: 'tool_result',
          tool_use_id: blk.id,
          content: 'Interrupted before the tool ran.',
          is_error: true
        })
      }
    }
  }
  content.push({ type: 'text', text: COMPACT_PROMPT })

  try {
    const resp = await client.messages.create({
      model: model.id,
      max_tokens: COMPACT_MAX_TOKENS,
      messages: [...chat.messages, { role: 'user', content }]
    })
    const summary = resp.content
      .filter((b): b is Anthropic.TextBlock => b.type === 'text')
      .map((b) => b.text)
      .join('\n')
      .trim()
    if (!summary) {
      return {
        ok: false,
        error: 'Compaction failed: the model returned no summary.'
      }
    }
    // Replace the history with a user/assistant pair so the next turn still
    // alternates roles cleanly.
    chat.messages.length = 0
    chat.messages.push(
      {
        role: 'user',
        content: `The earlier conversation was compacted to save context. Summary of everything so far:\n\n${summary}`
      },
      {
        role: 'assistant',
        content: 'Understood — continuing from that summary.'
      }
    )
    // The summary's output tokens approximate the new occupancy; the gauge
    // self-corrects with exact numbers on the next turn.
    return { ok: true, contextTokens: resp.usage.output_tokens }
  } catch (err) {
    return { ok: false, error: `Compaction failed: ${describeError(err)}` }
  }
}

/** Abort the stream and cancel the running statement. */
function stopChat(chatId: string): void {
  const chat = chats.get(chatId)
  if (!chat) return
  chat.controller?.abort()
  const cancel = chat.cancelRunningQuery
  if (cancel) {
    chat.cancelRunningQuery = null
    cancel()
  }
}

export function registerAgentHandlers(getWindow: () => BrowserWindow | null): void {
  const send: Sender = (evt) => {
    typedSend(getWindow(), 'agent:event', evt)
  }
  // Mirror the UI save path's push so the save_knowledge tool refreshes any
  // open renderer knowledge views. The event names the base plus every
  // (connection, database) target linked to it, so views keyed by target can
  // match without knowing the link table.
  setBroadcastKnowledgeChanged((kbId) => {
    const change: KnowledgeChangeEvent = { kbId, targets: targetsForBase(kbId) }
    typedSend(getWindow(), 'knowledge:changed', change)
  })

  // read_editor round-trip: main pushes a request id, the renderer replies on
  // agent:editor-read-reply with the live editor state. Timeouts resolve null
  // so a hung or reloading renderer degrades to "editor unavailable" instead
  // of wedging the turn.
  let editorReadSeq = 0
  const pendingEditorReads = new Map<string, (payload: AgentEditorReadPayload | null) => void>()
  typedOn('agent:editor-read-reply', (_event, requestId, payload) => {
    const resolve = pendingEditorReads.get(requestId)
    if (resolve) {
      pendingEditorReads.delete(requestId)
      resolve(payload)
    }
  })
  setReadEditorFromRenderer(() => {
    const win = getWindow()
    if (!win || win.isDestroyed()) return Promise.resolve(null)
    const requestId = `er${++editorReadSeq}`
    return new Promise((resolve) => {
      const timer = setTimeout(() => {
        pendingEditorReads.delete(requestId)
        resolve(null)
      }, EDITOR_READ_TIMEOUT_MS)
      pendingEditorReads.set(requestId, (payload) => {
        clearTimeout(timer)
        resolve(payload)
      })
      typedSend(win, 'agent:editor-read', requestId)
    })
  })

  typedHandle('agent:keyStatus', (): AgentKeyStatus => {
    const { key, source } = loadApiKey()
    return { found: key !== null, source, varName: apiKeyVarName() }
  })

  typedHandle('agent:send', async (_event, req) => {
    await runAgentTurn(req, send)
  })

  typedHandle('agent:stop', (_event, chatId) => {
    stopChat(chatId)
  })

  typedHandle('agent:compact', (_event, chatId, model): Promise<AgentCompactResult> =>
    compactChat(chatId, model)
  )

  typedHandle('agent:reset', (_event, chatId) => {
    stopChat(chatId)
    chats.delete(chatId)
    // Schema may have changed since it was cached; a fresh chat re-introspects.
    schemaCache.clear()
    introspectionCache.clear()
  })
}
