/**
 * Main-process AI agent: owns the Anthropic client, per-chat conversation
 * history, and the streaming tool-use loop. The renderer talks to it through
 * `agent:*` IPC handles and receives progress as `agent:event` pushes.
 *
 * Execution safety model: the user picks an access mode per chat. Metadata
 * Only offers no execution tools at all; Read-Only routes every statement
 * through runAgentQuery — the guarded channel that admits exactly one
 * provably-read statement per call, with the server-side read-only session
 * as a second belt. There is no approval flow: statements that modify data
 * or schema are blocked outright, in every mode.
 */

import { readFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

import Anthropic from '@anthropic-ai/sdk'
import { ipcMain } from 'electron'
import type { BrowserWindow } from 'electron'

import {
  AGENT_BLOCKED_CODE,
  describeTable,
  getConnectionType,
  getServerVersion,
  introspectDatabase,
  isReadOnlyViolation,
  runAgentQuery,
  searchSchema
} from './db'
import type {
  AgentCompactResult,
  AgentEvent,
  AgentKeyStatus,
  AgentMode,
  AgentSendRequest,
  AgentTargetRef
} from '../shared/agent'
import { AGENT_MODELS, API_KEY_VAR, resolveAgentMode } from '../shared/agent'
import { callMcpTool, mcpToolsForTurn } from './mcp'
import type { McpAgentTool } from './mcp'
import {
  getRepoCommit,
  getRepoRoot,
  grepRepo,
  listRepoFiles,
  readRepoFile
} from './repo'
import { listRecords, saveRecord } from './knowledge'
import { normalizeColumnKey } from '../shared/knowledge'
import type {
  AnnotationRecord,
  ColumnRef,
  ExemplarRecord,
  GlossaryRecord,
  KnowledgeKind,
  KnowledgeRecord,
  KnowledgeRecordInput,
  NoteRecord,
  RelationshipRecord
} from '../shared/knowledge'
import type { DatabaseIntrospection, QueryResult } from '../shared/db'
import { dialectFor } from '../shared/dialect'
import type { DialectInfo } from '../shared/dialect'
import { classifyStatement } from '../shared/sql'

/** Rows of a tool-run result forwarded to the model (grid shows the full set). */
const TOOL_RESULT_MAX_ROWS = 50
/** Overall budget for one tool-result payload sent to the model. */
const TOOL_RESULT_MAX_CHARS = 30_000
/** Per-cell cap applied (model copy only) when a payload exceeds the budget. */
const TOOL_RESULT_CELL_CHARS = 400
/** Auto-LIMIT applied to agent-run statements, mirroring the editor default. */
const TOOL_RUN_LIMIT = 500
/** statement_timeout for agent-issued statements. */
const AGENT_STATEMENT_TIMEOUT_MS = 30_000
/** Cap on the schema summary embedded in the system prompt. */
const SCHEMA_SUMMARY_MAX_CHARS = 48_000
/** Cap on the local-knowledge section embedded in the system prompt. */
export const KNOWLEDGE_SUMMARY_MAX_CHARS = 16_000
/** Cap on hits one search_knowledge call returns to the model. */
const KNOWLEDGE_SEARCH_MAX_HITS = 20
/** Per-hit cap on the rendered record text in a search_knowledge payload. */
const KNOWLEDGE_HIT_MAX_CHARS = 1_000
/** Cap on web searches the model may run in a single turn. */
const WEB_SEARCH_MAX_USES = 5

interface KeyInfo {
  key: string | null
  source: 'zshrc' | 'env' | null
}

function readKeyFromZshrc(): string | null {
  try {
    const text = readFileSync(join(homedir(), '.zshrc'), 'utf8')
    const re = new RegExp(`^\\s*(?:export\\s+)?${API_KEY_VAR}\\s*=\\s*["']?([^"'\\s#]+)`, 'gm')
    let match: RegExpExecArray | null
    let last: string | null = null
    while ((match = re.exec(text)) !== null) last = match[1]
    return last
  } catch {
    return null
  }
}

/** Re-read on every call so edits to ~/.zshrc apply without an app restart. */
function loadKey(): KeyInfo {
  const fromFile = readKeyFromZshrc()
  if (fromFile) return { key: fromFile, source: 'zshrc' }
  const fromEnv = process.env[API_KEY_VAR]
  if (fromEnv) return { key: fromEnv, source: 'env' }
  return { key: null, source: null }
}

interface ChatState {
  messages: Anthropic.MessageParam[]
  controller: AbortController | null
  /** Cancels the agent's currently running statement, when one is running. */
  cancelRunningQuery: (() => void) | null
  /**
   * Server-side code-execution container reported by the API when the
   * dynamic-filtering web search tool runs. Follow-up requests must echo its
   * id while the conversation has pending code-exec tool uses, or the API
   * rejects them ("container_id is required when there are pending tool
   * uses generated by code execution with tools").
   */
  container: { id: string; expiresAt: string } | null
}

const chats = new Map<string, ChatState>()

function getChat(chatId: string): ChatState {
  let chat = chats.get(chatId)
  if (!chat) {
    chat = {
      messages: [],
      controller: null,
      cancelRunningQuery: null,
      container: null
    }
    chats.set(chatId, chat)
  }
  return chat
}

/** Schema summaries are reused across turns; introspection can be slow. */
const schemaCache = new Map<string, string>()

/**
 * The introspection behind each cached summary, kept for save_knowledge ref
 * checking. Same key space and lifecycle as schemaCache (both clear on
 * agent:reset), so the two can never describe different snapshots.
 */
const introspectionCache = new Map<string, DatabaseIntrospection>()

function schemaCacheKey(target: AgentTargetRef): string {
  return `${target.connId}/${target.database}`
}

type ColumnLike = {
  name: string
  dataType: string
  badge: 'pk' | 'fk' | null
  fkRef?: string | null
}

function summarizeColumns(cols: ColumnLike[]): string {
  return cols
    .map((c) => {
      const marks: string[] = []
      if (c.badge === 'pk') marks.push('PK')
      if (c.fkRef) marks.push(`FK → ${c.fkRef}`)
      else if (c.badge === 'fk') marks.push('FK')
      return `${c.name} ${c.dataType}${marks.length > 0 ? ` [${marks.join(', ')}]` : ''}`
    })
    .join(', ')
}

/** 'full': types/keys/indexes; 'compact': column names only; 'names': relation names only. */
type SchemaDetail = 'full' | 'compact' | 'names'

function renderSchema(db: DatabaseIntrospection, detail: SchemaDetail): string {
  const lines: string[] = [`Database: ${db.name}`]
  for (const schema of db.schemas) {
    lines.push(`Schema "${schema.name}":`)
    if (detail === 'names') {
      const groups: [string, string[]][] = [
        ['tables', schema.tables.map((t) => t.name)],
        ['views', schema.views.map((v) => v.name)],
        ['materialized views', schema.matviews.map((m) => m.name)],
        ['functions', schema.functions.map((f) => f.name)]
      ]
      for (const [label, names] of groups) {
        if (names.length > 0) lines.push(`  ${label}: ${names.join(', ')}`)
      }
      continue
    }
    const renderRelation = (
      kind: string,
      rel: (typeof schema.tables)[number]
    ): void => {
      const cols =
        detail === 'full'
          ? summarizeColumns(rel.columns)
          : rel.columns.map((c) => c.name).join(', ')
      const rows =
        detail === 'full' && rel.rowEstimate != null && rel.rowEstimate >= 0
          ? ` ~${Math.round(rel.rowEstimate)} rows`
          : ''
      lines.push(`  ${kind} ${schema.name}.${rel.name} (${cols})${rows}`)
      if (detail === 'full' && rel.indexes && rel.indexes.length > 0) {
        lines.push(`    indexes: ${rel.indexes.join('; ')}`)
      }
    }
    for (const t of schema.tables) renderRelation('table', t)
    for (const v of schema.views) renderRelation('view', v)
    for (const m of schema.matviews) renderRelation('materialized view', m)
    for (const f of schema.functions) {
      lines.push(
        detail === 'full'
          ? `  function ${schema.name}.${f.name}(${f.args}) -> ${f.returnType}`
          : `  function ${schema.name}.${f.name}`
      )
    }
    if (schema.types.length > 0) {
      lines.push(
        `  types: ${schema.types
          .map((t) =>
            detail === 'full' && t.values && t.values.length > 0
              ? `${t.name} (enum: ${t.values.map((v) => `'${v}'`).join(', ')})`
              : `${t.name} (${t.kind})`
          )
          .join(', ')}`
      )
    }
  }
  return lines.join('\n')
}

/** Degrade detail tier by tier instead of cutting the summary mid-text. */
function summarizeSchema(db: DatabaseIntrospection): string {
  const full = renderSchema(db, 'full')
  if (full.length <= SCHEMA_SUMMARY_MAX_CHARS) return full
  const abridgedNote =
    '\n(schema summary abridged to fit context — use search_schema to locate names and describe_table for column, key, and index detail)'
  const compact = renderSchema(db, 'compact')
  if (compact.length + abridgedNote.length <= SCHEMA_SUMMARY_MAX_CHARS) {
    return compact + abridgedNote
  }
  const names = renderSchema(db, 'names')
  if (names.length + abridgedNote.length <= SCHEMA_SUMMARY_MAX_CHARS) {
    return names + abridgedNote
  }
  return (
    names.slice(0, SCHEMA_SUMMARY_MAX_CHARS - abridgedNote.length) +
    abridgedNote
  )
}

async function schemaSummaryFor(target: AgentTargetRef): Promise<string> {
  const cacheKey = schemaCacheKey(target)
  const cached = schemaCache.get(cacheKey)
  if (cached) return cached
  const res = await introspectDatabase(target.connId, target.database)
  if (!res.ok) return `(schema introspection failed: ${res.error})`
  const summary = summarizeSchema(res.data)
  schemaCache.set(cacheKey, summary)
  introspectionCache.set(cacheKey, res.data)
  return summary
}

/**
 * Every normalized ref key the live schema can satisfy — `schema.table` for
 * each relation plus `schema.table.column` for each column — or null when no
 * introspection has been cached for the target this session. Used to flag
 * (never block) save_knowledge records whose refs match nothing real.
 */
function liveRefKeys(target: AgentTargetRef): Set<string> | null {
  const db = introspectionCache.get(schemaCacheKey(target))
  if (!db) return null
  const keys = new Set<string>()
  for (const schema of db.schemas) {
    for (const rel of [...schema.tables, ...schema.views, ...schema.matviews]) {
      keys.add(normalizeColumnKey({ schema: schema.name, table: rel.name }))
      for (const col of rel.columns) {
        keys.add(
          normalizeColumnKey({
            schema: schema.name,
            table: rel.name,
            column: col.name
          })
        )
      }
    }
  }
  return keys
}

// --- Local knowledge (system-prompt section + search_knowledge) -------------
//
// The knowledge store is app-local: rendering it into the prompt and searching
// it never touches the warehouse, so these helpers carry no access-mode gate.
// Records are read fresh from listRecords on every prompt build (they are
// small), so saves and deletes take effect on the very next turn with no cache
// to invalidate — unlike the schema summary, which is introspection-priced and
// cached in schemaCache above.

/** The five kinds this build renders; unknown kinds are preserved on disk but skipped here. */
const KNOWN_KNOWLEDGE_KINDS = new Set<string>([
  'relationship',
  'glossary',
  'annotation',
  'exemplar',
  'note'
])

/**
 * Containment for every single-line interpolation of record content into the
 * prompt/tool output: newlines and control characters collapse to a space so
 * a field can never fabricate its own lines (fake headings, list items) —
 * knowledge records persist across conversations, so an uncontained field
 * would turn a one-time data-level injection into a durable prompt injection.
 * Tolerates non-strings (hand-edited files) rather than crashing the build.
 */
function singleLine(text: unknown): string {
  if (typeof text !== 'string') return ''
  // eslint-disable-next-line no-control-regex -- filtering control chars is the point
  return text.replace(/[\u0000-\u001f\u007f\u2028\u2029]+/g, ' ')
}

/** `schema.table` or `schema.table.column`, as prompt/search display text. */
function refName(ref: ColumnRef | undefined): string {
  if (!ref || typeof ref.schema !== 'string' || typeof ref.table !== 'string') {
    return '(invalid ref)'
  }
  return singleLine(
    ref.column
      ? `${ref.schema}.${ref.table}.${ref.column}`
      : `${ref.schema}.${ref.table}`
  )
}

/** Provenance marker so the model can weigh agent-inferred records. */
function sourceTag(rec: KnowledgeRecord): string {
  if (rec.source !== 'agent') return ''
  return rec.confidence
    ? ` [agent-recorded, ${rec.confidence} confidence]`
    : ' [agent-recorded]'
}

function quoteValue(value: string): string {
  return `'${singleLine(value).replace(/'/g, "''")}'`
}

/** Continuation lines of a multi-line value stay inside the list item. */
function indentBlock(text: unknown, prefix: string): string {
  const s = typeof text === 'string' ? text : ''
  return s.replace(/\r\n?/g, '\n').split('\n').join(`\n${prefix}`)
}

/**
 * One relationship as an explicit join instruction. Polymorphic joins spell
 * out every discriminator value → target pair and end with the warning the
 * model must not lose, e.g.: "public.events.subject_id joins to
 * public.patients.id when public.events.subject_type = 'patient', to
 * public.providers.id when 'provider'. Never join without filtering the
 * discriminator."
 */
function renderRelationship(rel: RelationshipRecord, withNotes: boolean): string {
  const notes = withNotes && rel.notes ? ` ${singleLine(rel.notes)}` : ''
  if (rel.relType === 'polymorphic' && rel.discriminator && rel.targets) {
    const disc = refName(rel.discriminator)
    const cases = Object.entries(rel.targets).map(([value, target], i) =>
      i === 0
        ? `to ${refName(target)} when ${disc} = ${quoteValue(value)}`
        : `to ${refName(target)} when ${quoteValue(value)}`
    )
    return `${refName(rel.from)} joins ${cases.join(', ')}. Never join without filtering the discriminator.${notes}`
  }
  const to = rel.to ? refName(rel.to) : '(target unspecified)'
  return `${refName(rel.from)} joins to ${to}.${notes}`
}

function renderGlossaryTerm(g: GlossaryRecord, detail: KnowledgeDetail): string {
  const synonyms = (g.synonyms ?? []).map(singleLine)
  const term = singleLine(g.term)
  const aka = synonyms.length > 0 ? ` (aka ${synonyms.join(', ')})` : ''
  if (detail === 'terms') return `- ${term}${aka}`
  const maps = (g.mappings ?? [])
    .map((m) => `${refName(m?.ref)}${m?.caveat ? ` (${singleLine(m.caveat)})` : ''}`)
    .join(', ')
  const def = g.definition ? `${singleLine(g.definition)}${maps ? ' — ' : ''}` : ''
  return `- ${term}${aka}: ${def}${maps ? `maps to ${maps}` : ''}${sourceTag(g)}`
}

/**
 * Degradation tiers for the prompt section, mirroring SchemaDetail: 'full' =
 * everything; 'no-note-bodies' = notes shrink to titles; 'no-exemplar-sql' =
 * exemplars additionally shrink to their questions; 'terms' = every record is
 * one compact line (titles/terms/targets only — join rules stay explicit
 * because they are the highest-stakes content).
 */
type KnowledgeDetail = 'full' | 'no-note-bodies' | 'no-exemplar-sql' | 'terms'

function renderKnowledge(records: KnowledgeRecord[], detail: KnowledgeDetail): string {
  const dropNoteBodies = detail !== 'full'
  const dropExemplarSql = detail === 'no-exemplar-sql' || detail === 'terms'
  const terms = detail === 'terms'

  const relationships = records.filter(
    (r): r is RelationshipRecord => r.kind === 'relationship'
  )
  const glossary = records.filter((r): r is GlossaryRecord => r.kind === 'glossary')
  const annotations = records.filter(
    (r): r is AnnotationRecord => r.kind === 'annotation'
  )
  const exemplars = records.filter((r): r is ExemplarRecord => r.kind === 'exemplar')
  const notes = records.filter((r): r is NoteRecord => r.kind === 'note')
  if (
    relationships.length + glossary.length + annotations.length +
      exemplars.length + notes.length === 0
  ) {
    return ''
  }

  const lines: string[] = [
    '## Local knowledge',
    'Knowledge recorded locally in DB Desk by the user and past agent sessions — business meaning and join rules the database catalog does not carry. Trust it when writing queries.'
  ]
  if (relationships.length > 0) {
    lines.push('', 'Relationships (join rules):')
    for (const rel of relationships) {
      lines.push(`- ${renderRelationship(rel, !terms)}${terms ? '' : sourceTag(rel)}`)
    }
  }
  if (glossary.length > 0) {
    lines.push('', 'Glossary:')
    for (const g of glossary) lines.push(renderGlossaryTerm(g, detail))
  }
  if (annotations.length > 0) {
    lines.push('', 'Annotations:')
    for (const a of annotations) {
      lines.push(
        terms
          ? `- ${refName(a.target)}`
          : `- ${refName(a.target)}: ${indentBlock(a.text, '  ')}${sourceTag(a)}`
      )
    }
  }
  if (exemplars.length > 0) {
    lines.push('', 'Exemplar queries (question → SQL):')
    for (const e of exemplars) {
      if (dropExemplarSql) {
        lines.push(`- Q: ${singleLine(e.question)}`)
      } else {
        lines.push(
          `- Q: ${singleLine(e.question)}${sourceTag(e)}`,
          `  SQL: ${indentBlock(e.sql, '  ')}`
        )
      }
    }
  }
  if (notes.length > 0) {
    lines.push('', 'Notes:')
    for (const n of notes) {
      if (dropNoteBodies) {
        lines.push(`- ${singleLine(n.title)}`)
      } else {
        lines.push(
          `- ${singleLine(n.title)}: ${indentBlock(n.body, '  ')}${sourceTag(n)}`
        )
        if ((n.references ?? []).length > 0) {
          lines.push(`  [refs: ${n.references.map(refName).join(', ')}]`)
        }
      }
    }
  }
  return lines.join('\n')
}

/**
 * The "## Local knowledge" prompt section, degrading tier by tier under its
 * budget instead of cutting mid-text (mirror of summarizeSchema). Empty store
 * renders nothing. Exported for unit tests.
 */
export function summarizeKnowledge(records: KnowledgeRecord[]): string {
  const full = renderKnowledge(records, 'full')
  if (full === '') return ''
  if (full.length <= KNOWLEDGE_SUMMARY_MAX_CHARS) return full
  const abridgedNote =
    '\n(local knowledge abridged to fit context — use search_knowledge to retrieve full entries)'
  for (const detail of ['no-note-bodies', 'no-exemplar-sql'] as const) {
    const rendered = renderKnowledge(records, detail)
    if (rendered.length + abridgedNote.length <= KNOWLEDGE_SUMMARY_MAX_CHARS) {
      return rendered + abridgedNote
    }
  }
  const minimal = renderKnowledge(records, 'terms')
  if (minimal.length + abridgedNote.length <= KNOWLEDGE_SUMMARY_MAX_CHARS) {
    return minimal + abridgedNote
  }
  return (
    minimal.slice(0, KNOWLEDGE_SUMMARY_MAX_CHARS - abridgedNote.length) +
    abridgedNote
  )
}

/** Every structured column reference a record carries, in a stable order. */
function knowledgeRefs(rec: KnowledgeRecord): ColumnRef[] {
  switch (rec.kind) {
    case 'annotation':
      return [rec.target]
    case 'relationship': {
      const refs: ColumnRef[] = []
      if (rec.from) refs.push(rec.from)
      if (rec.to) refs.push(rec.to)
      if (rec.discriminator) refs.push(rec.discriminator)
      if (rec.targets) refs.push(...Object.values(rec.targets))
      return refs
    }
    case 'glossary':
      return (rec.mappings ?? []).flatMap((m) => (m?.ref ? [m.ref] : []))
    case 'exemplar':
      return rec.references ?? []
    case 'note':
      return rec.references ?? []
    default:
      return []
  }
}

/** Lowercased searchable text: record prose plus every ref's name parts. */
function knowledgeHaystack(rec: KnowledgeRecord): string {
  const texts: string[] = []
  switch (rec.kind) {
    case 'annotation':
      texts.push(rec.text)
      break
    case 'relationship':
      if (rec.notes) texts.push(rec.notes)
      if (rec.targets) texts.push(...Object.keys(rec.targets))
      break
    case 'glossary':
      texts.push(rec.term, ...(rec.synonyms ?? []))
      if (rec.definition) texts.push(rec.definition)
      for (const m of rec.mappings ?? []) if (m?.caveat) texts.push(m.caveat)
      break
    case 'exemplar':
      texts.push(rec.question, rec.sql)
      break
    case 'note':
      texts.push(rec.title, rec.body)
      break
  }
  for (const ref of knowledgeRefs(rec)) {
    texts.push(ref.schema, ref.table)
    if (ref.column) texts.push(ref.column)
  }
  return texts.join('\n').toLowerCase()
}

/** Full one-record rendering for a search hit, capped per hit. */
function knowledgeHitSummary(rec: KnowledgeRecord): string {
  let text: string
  switch (rec.kind) {
    case 'annotation':
      text = `${refName(rec.target)}: ${rec.text}`
      break
    case 'relationship':
      text = renderRelationship(rec, true)
      break
    case 'glossary':
      text = renderGlossaryTerm(rec, 'full').replace(/^- /, '')
      break
    case 'exemplar':
      text = `Q: ${singleLine(rec.question)}\nSQL: ${rec.sql}`
      break
    case 'note':
      text = `${singleLine(rec.title)}: ${rec.body}`
      break
    default:
      text = ''
  }
  return text.length > KNOWLEDGE_HIT_MAX_CHARS
    ? `${text.slice(0, KNOWLEDGE_HIT_MAX_CHARS)}…`
    : text
}

/**
 * One search_knowledge hit. The id matters: the agent write path updates
 * existing records by id, and search_knowledge is where the model gets them.
 */
export interface KnowledgeSearchHit {
  id: string
  kind: KnowledgeKind
  refs: ColumnRef[]
  summary: string
}

/**
 * Case-insensitive keyword search (every whitespace-separated keyword must
 * match) over record text — glossary terms/synonyms/definitions, annotation
 * text, note titles/bodies, exemplar questions/SQL, relationship notes and
 * discriminator values — plus the schema/table/column names inside structured
 * refs. Pure and local; never touches the warehouse. Exported for unit tests.
 */
export function searchKnowledgeRecords(
  records: KnowledgeRecord[],
  query: string
): KnowledgeSearchHit[] {
  const keywords = query.toLowerCase().split(/\s+/).filter(Boolean)
  if (keywords.length === 0) return []
  const hits: KnowledgeSearchHit[] = []
  for (const rec of records) {
    if (!KNOWN_KNOWLEDGE_KINDS.has(rec.kind)) continue
    const haystack = knowledgeHaystack(rec)
    if (keywords.every((k) => haystack.includes(k))) {
      hits.push({
        id: rec.id,
        kind: rec.kind,
        refs: knowledgeRefs(rec),
        summary: knowledgeHitSummary(rec)
      })
    }
  }
  return hits
}

/**
 * Local annotations and relationships touching one table, appended to
 * describe_table output after the DB-native detail. `name` is the tool input
 * ("orders" or "sales.orders"); matching is case-insensitive and, when no
 * schema is given, spans all schemas. Returns null when nothing is recorded.
 * Exported for unit tests.
 */
export function renderTableKnowledge(
  records: KnowledgeRecord[],
  name: string
): string | null {
  const parts = name.toLowerCase().split('.').filter(Boolean)
  if (parts.length === 0) return null
  const table = parts[parts.length - 1]
  const schema = parts.length > 1 ? parts[parts.length - 2] : null
  const matches = (ref: ColumnRef | undefined): boolean =>
    ref !== undefined &&
    ref.table.toLowerCase() === table &&
    (schema === null || ref.schema.toLowerCase() === schema)
  const annotations = records.filter(
    (r): r is AnnotationRecord => r.kind === 'annotation' && matches(r.target)
  )
  const relationships = records.filter(
    (r): r is RelationshipRecord =>
      r.kind === 'relationship' &&
      (matches(r.from) ||
        matches(r.to) ||
        matches(r.discriminator) ||
        Object.values(r.targets ?? {}).some(matches))
  )
  if (annotations.length === 0 && relationships.length === 0) return null
  const lines: string[] = [
    'local knowledge (recorded in DB Desk, not from the database catalog):'
  ]
  if (annotations.length > 0) {
    lines.push('annotations:')
    for (const a of annotations) {
      lines.push(
        `  ${refName(a.target)}: ${indentBlock(a.text, '    ')}${sourceTag(a)}`
      )
    }
  }
  if (relationships.length > 0) {
    lines.push('relationships:')
    for (const rel of relationships) {
      lines.push(`  ${renderRelationship(rel, true)}${sourceTag(rel)}`)
    }
  }
  return lines.join('\n')
}

/** Exported for unit tests. */
/** Repo facts injected into the system prompt when a codebase is attached. */
export interface RepoPromptInfo {
  root: string
  commit: string | null
}

export function buildSystemPrompt(
  req: AgentSendRequest,
  mode: AgentMode,
  schemaSummary: string | null,
  dialect: DialectInfo,
  mcpTools: McpAgentTool[],
  repo?: RepoPromptInfo | null
): string {
  const parts: string[] = [
    'You are the AI assistant inside DB Desk, a desktop database client.',
    `Your job is to turn user requests into correct, working ${dialect.engine} statements.`,
    '',
    'Rules:',
    '- Always put final, runnable SQL inside ```sql fenced code blocks; the user can insert those blocks into their editor with one click.',
    '- When you have settled on the final query, call the write_to_editor tool with it so it lands in the SQL editor. Do this once per answer, at the end, with the single final statement — not with intermediate or exploratory queries.',
    ...dialect.agent.rules,
    '- Keep prose brief; lead with the SQL, then a short explanation if needed.'
  ]
  if (req.target && mode === 'read-only') {
    parts.push(
      '- You may execute statements with the run_sql tool. Use it to validate your SQL and inspect real data before presenting a final answer. Each run is shown to the user in the results grid.',
      '- You are in Read-Only mode: one statement per run_sql call, and only read-only statements (SELECT, WITH, SHOW, DESCRIBE, EXPLAIN of reads) will execute. Anything that would modify data or schema — including INSERT/UPDATE/DELETE/MERGE, DDL, SET, and transaction control — is blocked before it reaches the server and will fail. Do not attempt such statements. If the user asks for a change, write the SQL to the editor with write_to_editor and tell them to review and run it themselves.',
      `- Statements are cancelled after ${AGENT_STATEMENT_TIMEOUT_MS / 1000} seconds.`,
      `- Use describe_table for full detail on one relation and search_schema to find tables, columns, or functions by name — ${dialect.agent.catalogHint}.`,
      (dialect.agent.supportsExplainAnalyze
        ? '- Use explain_query to inspect query plans before recommending a query on large tables; set analyze to true only when actually executing a read is acceptable.'
        : '- Use explain_query to inspect query plans before recommending a query on large tables.') +
        ' EXPLAIN is refused for statements that modify data or schema.'
    )
  } else if (req.target) {
    parts.push(
      '- You are in Metadata Only mode: you cannot execute anything against the database. Work from the schema summary below and the objects the user attached. Do not claim to have run or validated anything; present SQL for the user to run.'
    )
  } else {
    parts.push(
      '- Query execution is disabled for this chat; do not claim to have run anything.'
    )
  }
  if (req.target) {
    parts.push(
      '- Use search_knowledge to look up locally recorded knowledge about this database — glossary terms, join rules, annotations, exemplar queries, notes. It reads only the local DB Desk store, never the database, so it is available in every mode.',
      '- Use save_knowledge to record a durable fact the user states about their data — what a column really means, a join rule (including polymorphic joins), a glossary term, or a good example query — so it survives chat resets and helps future conversations. Save only what changes how a query would be written, and keep it terse: 1-3 plain sentences, no restating the schema — the whole store is injected into every future prompt under a fixed budget. Do not save conversation-local trivia, one-off answers, or anything you are unsure about. To correct or extend an existing record, pass the id from a search_knowledge result so it updates in place rather than duplicating. It writes only the local store, never the database, so it is available in every mode.'
    )
  }
  if (req.webSearch) {
    parts.push(
      '- Web search is enabled for this chat. You may search the web when outside information would genuinely help — engine documentation, SQL syntax and function references, unfamiliar error messages, or examples the user asked for. Most requests are answerable from the schema and your own knowledge; do not search for those.'
    )
  }
  if (mcpTools.length > 0) {
    parts.push(
      '- Tools named mcp__* come from MCP servers the user configured. They act on external systems with whatever access the user granted those servers; they are separate from the connected database and from the read/write rules above, which apply only to the SQL tools. Use them when the request calls for it.'
    )
  }
  if (repo) {
    parts.push(
      `- The codebase that owns this database is attached read-only at "${repo.root}"${repo.commit ? ` (git commit ${repo.commit})` : ''}. Use list_repo_files, grep_repo, and read_repo_file to consult it: migrations, ORM models, query layers, and docs often explain what the schema alone cannot — especially undeclared joins and polymorphic associations. All paths are relative to that root; secret-bearing files (.env, keys) are not accessible.`,
      `- When you save knowledge derived from the codebase, set provenance to the source file path${repo.commit ? ` at this commit, e.g. "db/migrate/x.rb@${repo.commit}"` : ''}, and verify every schema/table/column reference against the live schema first. Where code and database disagree, trust the database and lower the confidence.`
    )
  }
  if (req.target) {
    const version = getServerVersion(req.target.connId)
    parts.push(
      '',
      `Connected target: connection "${req.target.connName}", ${dialect.databaseTerm} "${req.target.database}"${version ? ` (${dialect.engine} ${version})` : ` (${dialect.engine})`}.`
    )
  } else {
    parts.push(
      '',
      'No database is connected; write SQL from the request alone.'
    )
  }
  if (req.context.length > 0) {
    parts.push(
      '',
      'The user attached these database objects to the thread as context — treat them as the primary subjects of the request:'
    )
    for (const item of req.context) {
      const qualified = item.schema ? `${item.schema}.${item.name}` : item.name
      const elsewhere =
        !req.target ||
        item.connId !== req.target.connId ||
        item.database !== req.target.database
          ? ` (in database "${item.database}", not the connected target)`
          : ''
      parts.push(`- ${item.kind} ${qualified}${elsewhere}`)
    }
    if (req.target) {
      parts.push(
        'Use describe_table on the attached tables and views when column-level detail matters.'
      )
    }
  }
  if (schemaSummary) {
    parts.push('', 'Database schema:', schemaSummary)
  }
  if (req.target) {
    // Read fresh on every build (records are small); saves and deletes —
    // from the UI or the agent's own tools — apply on the next turn without
    // any cache to invalidate.
    const knowledge = summarizeKnowledge(
      listRecords(req.target.connId, req.target.database)
    )
    if (knowledge) parts.push('', knowledge)
  }
  if (req.editor && req.editor.sql.trim()) {
    parts.push(
      '',
      `Active editor file${req.editor.fileName ? ` (${req.editor.fileName})` : ''} contents:`,
      '```sql',
      req.editor.sql,
      '```'
    )
  }
  return parts.join('\n')
}

function runSqlTool(dialect: DialectInfo): Anthropic.Tool {
  return {
    name: 'run_sql',
    description: `Execute a single read-only SQL statement against the connected ${dialect.engine} ${dialect.databaseTerm} and return the result. Exactly one statement per call. Statements that modify data or schema — or anything not provably a read — are blocked and fail. SELECT results are limited to 500 rows and the first 50 rows are returned to you; the full result is shown to the user in the results grid. Use this to validate queries and check real data.`,
    input_schema: {
      type: 'object',
      properties: {
        sql: {
          type: 'string',
          description: `A single ${dialect.engine} statement to execute.`
        }
      },
      required: ['sql']
    }
  }
}

function explainQueryTool(dialect: DialectInfo): Anthropic.Tool {
  const analyzeProps: Record<string, unknown> = dialect.agent
    .supportsExplainAnalyze
    ? {
        analyze: {
          type: 'boolean',
          description:
            'Execute the statement to collect real timings (EXPLAIN ANALYZE). Reads only.'
        }
      }
    : {}
  return {
    name: 'explain_query',
    description: dialect.agent.supportsExplainAnalyze
      ? 'Run EXPLAIN on a SQL statement and return the query plan as text. Set analyze to true to execute the statement and get actual timings and row counts. Use this to check whether a query uses indexes before recommending it. Statements that modify data or schema cannot be explained.'
      : 'Run EXPLAIN on a SQL statement and return the query plan as text, without executing the statement. Use this to sanity-check how a query will be executed before recommending it. Statements that modify data or schema cannot be explained.',
    input_schema: {
      type: 'object',
      properties: {
        sql: {
          type: 'string',
          description: `A single ${dialect.engine} statement to explain.`
        },
        ...analyzeProps
      },
      required: ['sql']
    }
  }
}

function describeTableTool(dialect: DialectInfo): Anthropic.Tool {
  return {
    name: 'describe_table',
    description: `Return full detail for one table, view, or materialized view: columns with types and comments, plus whatever the engine tracks — constraints, indexes, defaults, row estimates, storage detail. ${dialect.agent.catalogHint.replace(/^prefer/, 'Prefer')}.`,
    input_schema: {
      type: 'object',
      properties: {
        name: {
          type: 'string',
          description:
            'Relation name, optionally schema-qualified (e.g. "orders" or "sales.orders").'
        }
      },
      required: ['name']
    }
  }
}

function searchSchemaTool(dialect: DialectInfo): Anthropic.Tool {
  return {
    name: 'search_schema',
    description: `Case-insensitive substring search over table, view, column, and function names in the connected ${dialect.databaseTerm}. Use this to locate where a piece of data lives when the schema summary is abridged or a name is unknown.`,
    input_schema: {
      type: 'object',
      properties: {
        pattern: {
          type: 'string',
          description: 'Substring to search for, e.g. "order_total".'
        }
      },
      required: ['pattern']
    }
  }
}

/**
 * Purely local tool: searches the DB Desk knowledge store, never the
 * warehouse, so — unlike the SQL tools — it is offered in Metadata Only mode
 * too and carries no access-mode gate.
 */
const SEARCH_KNOWLEDGE_TOOL: Anthropic.Tool = {
  name: 'search_knowledge',
  description:
    'Keyword search over the local knowledge store for the connected database: glossary terms and synonyms, table/column annotations, join relationships (including polymorphic join rules), exemplar question→SQL pairs, and notes recorded by the user or past agent sessions. Matches record text and the schema/table/column names in structured references. Returns hits with the record id, kind, refs, and content. Reads only the local store — it never queries the database — and is available in every access mode.',
  input_schema: {
    type: 'object',
    properties: {
      query: {
        type: 'string',
        description:
          'Keywords to search for (all must match), e.g. "MRN" or "orders join".'
      }
    },
    required: ['query']
  }
}

/** JSON-schema fragment for a structured column/table reference. */
const COLUMN_REF_SCHEMA = {
  type: 'object',
  properties: {
    schema: { type: 'string' },
    table: { type: 'string' },
    column: {
      type: 'string',
      description: 'Omit for a reference to the whole table.'
    }
  },
  required: ['schema', 'table']
} as const

/**
 * Write path into the local knowledge store. Like search_knowledge this never
 * touches the warehouse — it only writes DB Desk's app-local records — so it is
 * offered in Metadata Only as well as Read-Only. The record shape is validated
 * with the same `validateKnowledgeRecord` the UI save path uses; `source` is
 * forced to 'agent' by the handler. Kind-specific fields are all optional at
 * the schema level and enforced per-kind by validation, so one flat schema
 * covers every record kind.
 */
const SAVE_KNOWLEDGE_TOOL: Anthropic.Tool = {
  name: 'save_knowledge',
  description:
    'Record a durable fact about this database in the local DB Desk knowledge store so it survives chat resets and informs future conversations. Use it when the user states a lasting truth about their data — what a column really means, a join rule (including polymorphic joins), a glossary term, or a good example query. Save only facts that change how a query would be written, and write them terse: 1-3 plain sentences, no markdown emphasis, no restating the schema (the whole store renders into every future prompt under a fixed budget). Do NOT save conversation-local trivia, one-off answers, or anything you are unsure about. To correct or extend an existing record, pass its `id` from a search_knowledge result so it is updated in place instead of duplicated. Records you write are marked as agent-sourced; set `confidence` to reflect how sure you are. Writes only the local store, never the database, so it is available in every access mode.',
  input_schema: {
    type: 'object',
    properties: {
      id: {
        type: 'string',
        description:
          'Omit to create a new record. Pass an id from search_knowledge to update that existing record in place.'
      },
      kind: {
        type: 'string',
        enum: ['annotation', 'relationship', 'glossary', 'exemplar', 'note'],
        description: 'Which record kind to save; determines the required fields.'
      },
      confidence: {
        type: 'string',
        enum: ['high', 'medium', 'low'],
        description: 'How sure you are of this fact.'
      },
      provenance: {
        type: 'string',
        description: 'Optional note on where this fact came from.'
      },
      target: {
        ...COLUMN_REF_SCHEMA,
        description: 'annotation: the table or column this describes.'
      },
      text: {
        type: 'string',
        description: 'annotation: markdown description, caveat, or gotcha.'
      },
      relType: {
        type: 'string',
        enum: ['standard', 'polymorphic'],
        description: 'relationship: standard single-target join, or polymorphic.'
      },
      from: {
        ...COLUMN_REF_SCHEMA,
        description: 'relationship: the local (foreign-key) column; a column is required.'
      },
      to: {
        ...COLUMN_REF_SCHEMA,
        description: 'relationship (standard): the single join target column.'
      },
      discriminator: {
        ...COLUMN_REF_SCHEMA,
        description: 'relationship (polymorphic): the column whose value selects the target.'
      },
      targets: {
        type: 'object',
        description:
          'relationship (polymorphic): map of discriminator value -> join target ColumnRef.',
        additionalProperties: COLUMN_REF_SCHEMA
      },
      notes: {
        type: 'string',
        description: 'relationship: optional free-form join notes.'
      },
      term: { type: 'string', description: 'glossary: the business term.' },
      synonyms: {
        type: 'array',
        items: { type: 'string' },
        description: 'glossary: alternate names for the term (may be empty).'
      },
      definition: {
        type: 'string',
        description: 'glossary: optional definition of the term.'
      },
      mappings: {
        type: 'array',
        description: 'glossary: which columns realize this term.',
        items: {
          type: 'object',
          properties: {
            ref: COLUMN_REF_SCHEMA,
            caveat: { type: 'string' }
          },
          required: ['ref']
        }
      },
      question: {
        type: 'string',
        description: 'exemplar: the natural-language question.'
      },
      sql: { type: 'string', description: 'exemplar: the SQL that answers it.' },
      title: { type: 'string', description: 'note: a short title.' },
      body: { type: 'string', description: 'note: markdown body.' },
      references: {
        type: 'array',
        items: COLUMN_REF_SCHEMA,
        description:
          'exemplar & note: every table/column the record refers to, as structured refs (required so usage lookups can find it — prose mentions do not count).'
      }
    },
    required: ['kind']
  }
}

/**
 * Repo tools: read-only, sandboxed access to the codebase attached to the
 * connection (see repo.ts for the sandbox invariants). Offered only when the
 * user enabled the codebase toggle AND main has a configured root for the
 * target connection — the model never supplies or learns absolute paths
 * beyond the root shown in the system prompt.
 */
const LIST_REPO_FILES_TOOL: Anthropic.Tool = {
  name: 'list_repo_files',
  description:
    'List files in the attached codebase. Returns repo-relative paths. Skips dot-directories, vendored/build directories (node_modules, dist, …), and credential files. A glob without "/" matches basenames anywhere (e.g. "*.rb"); with "/" it matches the full relative path ("db/migrate/**"). Results are capped; narrow with dir/glob when truncated.',
  input_schema: {
    type: 'object',
    properties: {
      dir: {
        type: 'string',
        description: 'Directory to list from, relative to the repo root. Default: the root.'
      },
      glob: {
        type: 'string',
        description: 'Optional filter supporting **, *, and ?, e.g. "**/*.sql" or "*.prisma".'
      }
    }
  }
}

const GREP_REPO_TOOL: Anthropic.Tool = {
  name: 'grep_repo',
  description:
    'Search file contents in the attached codebase with a JavaScript regular expression (case-insensitive unless caseSensitive is true). Returns matching lines as path:line pairs, capped at 200 matches. Binary files, oversized files, and credential files are skipped. Narrow with dir/glob for focused searches.',
  input_schema: {
    type: 'object',
    properties: {
      pattern: {
        type: 'string',
        description: 'Regular expression to search for, e.g. "belongs_to|has_many" or "CREATE TABLE".'
      },
      dir: {
        type: 'string',
        description: 'Directory to search under, relative to the repo root. Default: the root.'
      },
      glob: {
        type: 'string',
        description: 'Optional filename filter supporting **, *, and ?, e.g. "*.py".'
      },
      caseSensitive: {
        type: 'boolean',
        description: 'Match case-sensitively. Default false.'
      }
    },
    required: ['pattern']
  }
}

const READ_REPO_FILE_TOOL: Anthropic.Tool = {
  name: 'read_repo_file',
  description:
    'Read a file from the attached codebase. Path is relative to the repo root. Returns up to 500 lines per call by default; use offset/limit to page through longer files. Binary and credential files are refused.',
  input_schema: {
    type: 'object',
    properties: {
      path: {
        type: 'string',
        description: 'Repo-relative file path, e.g. "db/schema.rb".'
      },
      offset: {
        type: 'number',
        description: '1-based line number to start from. Default 1.'
      },
      limit: {
        type: 'number',
        description: 'Maximum lines to return. Default 500.'
      }
    },
    required: ['path']
  }
}

/**
 * Server-side web search tool, executed on Anthropic's infrastructure.
 * Haiku 4.5 predates the dynamic-filtering variant and needs the basic one.
 */
function webSearchTool(modelId: string): Anthropic.Messages.ToolUnion {
  if (modelId === 'claude-haiku-4-5') {
    return {
      type: 'web_search_20250305',
      name: 'web_search',
      max_uses: WEB_SEARCH_MAX_USES
    }
  }
  return {
    type: 'web_search_20260209',
    name: 'web_search',
    max_uses: WEB_SEARCH_MAX_USES
  }
}

const WRITE_EDITOR_TOOL: Anthropic.Tool = {
  name: 'write_to_editor',
  description:
    "Insert SQL into the user's active SQL editor at the cursor. Call this once at the end of your answer with the final, validated query so the user has it ready to run. Do not call it for intermediate or exploratory queries.",
  input_schema: {
    type: 'object',
    properties: {
      sql: {
        type: 'string',
        description: 'The final SQL to place in the editor.'
      }
    },
    required: ['sql']
  }
}

function toolResultPayload(result: QueryResult): string {
  let rows = result.rows.slice(0, TOOL_RESULT_MAX_ROWS)
  let cellCap: number | null = null

  const build = (): string => {
    const notes: string[] = []
    if (result.rows.length > rows.length) {
      notes.push(
        `showing first ${rows.length} of ${result.rows.length} fetched rows`
      )
    }
    if (result.limitApplied !== null) {
      notes.push(
        `a LIMIT ${result.limitApplied} was auto-appended; the full result may have more rows`
      )
    }
    if (result.truncated) {
      notes.push(
        'rows beyond the fetch limit were discarded; the full result has more rows'
      )
    }
    if (cellCap !== null) {
      notes.push(
        `long cell values truncated to ${cellCap} chars in this payload`
      )
    }
    const cap = cellCap
    const outRows =
      cap === null
        ? rows
        : rows.map((row) =>
            row.map((cell) =>
              typeof cell === 'string' && cell.length > cap
                ? `${cell.slice(0, cap)}…`
                : cell
            )
          )
    return JSON.stringify({
      command: result.command,
      rowCount: result.rowCount,
      durationMs: result.durationMs,
      fields: result.fields,
      rows: outRows,
      note: notes.length > 0 ? notes.join('; ') : undefined
    })
  }

  let payload = build()
  if (payload.length > TOOL_RESULT_MAX_CHARS) {
    cellCap = TOOL_RESULT_CELL_CHARS
    payload = build()
  }
  while (payload.length > TOOL_RESULT_MAX_CHARS && rows.length > 1) {
    rows = rows.slice(0, Math.ceil(rows.length / 2))
    payload = build()
  }
  return payload
}

type Sender = (evt: AgentEvent) => void

/**
 * Fires the same `knowledge:changed` push the UI save path emits (see
 * registerKnowledgeHandlers in index.ts) so renderer knowledge views refresh
 * when the agent's save_knowledge tool writes a record. Set in
 * registerAgentHandlers; a no-op until then (e.g. in unit tests) so the write
 * still succeeds without a window.
 */
let broadcastKnowledgeChanged: (connId: string, database: string) => void = () => {}

function toolError(
  base: Anthropic.ToolResultBlockParam,
  req: AgentSendRequest,
  toolId: string,
  send: Sender,
  summary: string,
  content: string
): Anthropic.ToolResultBlockParam {
  send({ type: 'tool_result', chatId: req.chatId, toolId, ok: false, summary })
  return { ...base, content, is_error: true }
}

async function execRunSql(
  req: AgentSendRequest,
  chat: ChatState,
  mode: AgentMode,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Promise<Anthropic.ToolResultBlockParam> {
  const sql = String((block.input as { sql?: unknown }).sql ?? '').trim()
  const base: Anthropic.ToolResultBlockParam = {
    type: 'tool_result',
    tool_use_id: block.id,
    content: ''
  }
  if (mode !== 'read-only') {
    return toolError(
      base,
      req,
      block.id,
      send,
      'not available',
      'This tool is not available in Metadata Only mode.'
    )
  }
  const target = req.target
  if (!target) {
    return toolError(
      base,
      req,
      block.id,
      send,
      'no target',
      'No database target is connected.'
    )
  }
  send({
    type: 'tool_start',
    chatId: req.chatId,
    toolId: block.id,
    name: block.name,
    sql
  })

  const res = await runAgentQuery(
    target.connId,
    target.database,
    sql,
    TOOL_RUN_LIMIT,
    {
      timeoutMs: AGENT_STATEMENT_TIMEOUT_MS,
      onCancel: (cancel) => {
        chat.cancelRunningQuery = cancel
      }
    }
  )
  chat.cancelRunningQuery = null

  // Blocked by the guard (Layer 2) or the server-side belt (Layer 3): same
  // friendly refusal either way, and never an approval request.
  if (!res.ok && res.code === AGENT_BLOCKED_CODE) {
    return toolError(base, req, block.id, send, 'blocked', res.error)
  }
  if (!res.ok && isReadOnlyViolation(res.code)) {
    return toolError(
      base,
      req,
      block.id,
      send,
      'blocked',
      'Blocked: this statement modifies data. The agent is read-only; write the SQL to the editor for the user to review and run.'
    )
  }

  send({
    type: 'ran_query',
    chatId: req.chatId,
    sql,
    target,
    result: res.ok ? res.data : null,
    error: res.ok ? null : res.error
  })
  if (!res.ok) {
    return toolError(
      base,
      req,
      block.id,
      send,
      res.error,
      `Query failed: ${res.error}`
    )
  }
  const summary =
    res.data.rowCount === null
      ? res.data.command
      : `${res.data.command} · ${res.data.rowCount} row${res.data.rowCount === 1 ? '' : 's'} · ${res.data.durationMs}ms`
  send({
    type: 'tool_result',
    chatId: req.chatId,
    toolId: block.id,
    ok: true,
    summary
  })
  return { ...base, content: toolResultPayload(res.data) }
}

async function execExplain(
  req: AgentSendRequest,
  chat: ChatState,
  mode: AgentMode,
  block: Anthropic.ToolUseBlock,
  send: Sender,
  dialect: DialectInfo
): Promise<Anthropic.ToolResultBlockParam> {
  const input = block.input as { sql?: unknown; analyze?: unknown }
  const sql = String(input.sql ?? '').trim()
  const analyze = input.analyze === true && dialect.agent.supportsExplainAnalyze
  const base: Anthropic.ToolResultBlockParam = {
    type: 'tool_result',
    tool_use_id: block.id,
    content: ''
  }
  if (mode !== 'read-only') {
    return toolError(
      base,
      req,
      block.id,
      send,
      'not available',
      'This tool is not available in Metadata Only mode.'
    )
  }
  const target = req.target
  if (!target) {
    return toolError(
      base,
      req,
      block.id,
      send,
      'no target',
      'No database target is connected.'
    )
  }
  // Writes are not explained at all (with or without ANALYZE); refuse the
  // inner statement up front instead of relying on a downstream failure.
  if (classifyStatement(sql) !== 'read') {
    return toolError(
      base,
      req,
      block.id,
      send,
      'blocked',
      'Blocked: EXPLAIN is not available for statements that modify data or schema.'
    )
  }
  const explainSql = dialect.explainSql(sql, analyze)
  send({
    type: 'tool_start',
    chatId: req.chatId,
    toolId: block.id,
    name: block.name,
    sql: explainSql
  })
  const res = await runAgentQuery(
    target.connId,
    target.database,
    explainSql,
    null,
    {
      timeoutMs: AGENT_STATEMENT_TIMEOUT_MS,
      onCancel: (cancel) => {
        chat.cancelRunningQuery = cancel
      }
    }
  )
  chat.cancelRunningQuery = null
  if (!res.ok) {
    return toolError(
      base,
      req,
      block.id,
      send,
      res.error,
      `EXPLAIN failed: ${res.error}`
    )
  }
  const plan = res.data.rows.map((row) => row[0]).join('\n')
  send({
    type: 'tool_result',
    chatId: req.chatId,
    toolId: block.id,
    ok: true,
    summary: `plan · ${res.data.durationMs}ms`
  })
  return { ...base, content: plan || '(empty plan)' }
}

async function execDescribeTable(
  req: AgentSendRequest,
  mode: AgentMode,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Promise<Anthropic.ToolResultBlockParam> {
  const name = String((block.input as { name?: unknown }).name ?? '').trim()
  const base: Anthropic.ToolResultBlockParam = {
    type: 'tool_result',
    tool_use_id: block.id,
    content: ''
  }
  if (mode !== 'read-only') {
    return toolError(
      base,
      req,
      block.id,
      send,
      'not available',
      'This tool is not available in Metadata Only mode.'
    )
  }
  const target = req.target
  if (!target) {
    return toolError(
      base,
      req,
      block.id,
      send,
      'no target',
      'No database target is connected.'
    )
  }
  send({
    type: 'tool_start',
    chatId: req.chatId,
    toolId: block.id,
    name: block.name,
    sql: `describe ${name}`
  })
  const res = await describeTable(target.connId, target.database, name)
  if (!res.ok) {
    return toolError(
      base,
      req,
      block.id,
      send,
      res.error,
      `describe_table failed: ${res.error}`
    )
  }
  send({
    type: 'tool_result',
    chatId: req.chatId,
    toolId: block.id,
    ok: true,
    summary: name
  })
  // Locally recorded annotations and relationships ride along after the
  // DB-native detail so one describe_table call carries both.
  const local = renderTableKnowledge(
    listRecords(target.connId, target.database),
    name
  )
  return { ...base, content: local ? `${res.data}\n\n${local}` : res.data }
}

async function execSearchSchema(
  req: AgentSendRequest,
  mode: AgentMode,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Promise<Anthropic.ToolResultBlockParam> {
  const pattern = String(
    (block.input as { pattern?: unknown }).pattern ?? ''
  ).trim()
  const base: Anthropic.ToolResultBlockParam = {
    type: 'tool_result',
    tool_use_id: block.id,
    content: ''
  }
  if (mode !== 'read-only') {
    return toolError(
      base,
      req,
      block.id,
      send,
      'not available',
      'This tool is not available in Metadata Only mode.'
    )
  }
  const target = req.target
  if (!target) {
    return toolError(
      base,
      req,
      block.id,
      send,
      'no target',
      'No database target is connected.'
    )
  }
  send({
    type: 'tool_start',
    chatId: req.chatId,
    toolId: block.id,
    name: block.name,
    sql: `search "${pattern}"`
  })
  const res = await searchSchema(target.connId, target.database, pattern)
  if (!res.ok) {
    return toolError(
      base,
      req,
      block.id,
      send,
      res.error,
      `search_schema failed: ${res.error}`
    )
  }
  const matches = res.data.startsWith('No relations')
    ? 'no matches'
    : 'matches found'
  send({
    type: 'tool_result',
    chatId: req.chatId,
    toolId: block.id,
    ok: true,
    summary: matches
  })
  return { ...base, content: res.data }
}

/**
 * search_knowledge: local store lookup only. No access-mode check on purpose —
 * the mode protects the connected database, and this tool never proxies SQL or
 * touches the warehouse in any mode. Exported for unit tests.
 */
export function execSearchKnowledge(
  req: AgentSendRequest,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Anthropic.ToolResultBlockParam {
  const query = String((block.input as { query?: unknown }).query ?? '').trim()
  const base: Anthropic.ToolResultBlockParam = {
    type: 'tool_result',
    tool_use_id: block.id,
    content: ''
  }
  const target = req.target
  if (!target) {
    return toolError(
      base,
      req,
      block.id,
      send,
      'no target',
      'No database target is connected.'
    )
  }
  send({
    type: 'tool_start',
    chatId: req.chatId,
    toolId: block.id,
    name: block.name,
    sql: `search knowledge "${query}"`
  })
  const all = searchKnowledgeRecords(
    listRecords(target.connId, target.database),
    query
  )
  const hits = all.slice(0, KNOWLEDGE_SEARCH_MAX_HITS)
  send({
    type: 'tool_result',
    chatId: req.chatId,
    toolId: block.id,
    ok: true,
    summary: `${all.length} match${all.length === 1 ? '' : 'es'}`
  })
  return {
    ...base,
    content: JSON.stringify({
      hits,
      note:
        all.length > hits.length
          ? `showing first ${hits.length} of ${all.length} matches — refine the query for the rest`
          : undefined
    })
  }
}

/**
 * save_knowledge: writes one record into the local knowledge store. No
 * access-mode gate on purpose — it only writes DB Desk's app-local store, never
 * the warehouse — but it does require a connected target (records are keyed to
 * connId + database). `source` is forced to 'agent'; the record is validated
 * with the same `validateKnowledgeRecord` the UI save path uses (via
 * saveRecord), so malformed payloads become a useful tool error rather than a
 * bad write. A present `id` that matches an existing record updates it in place
 * (preserving createdAt, stamping updatedAt); otherwise a new record is minted.
 * On success it fires the `knowledge:changed` push so open knowledge views
 * refresh. Exported for unit tests.
 */
export function execSaveKnowledge(
  req: AgentSendRequest,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Anthropic.ToolResultBlockParam {
  const base: Anthropic.ToolResultBlockParam = {
    type: 'tool_result',
    tool_use_id: block.id,
    content: ''
  }
  const target = req.target
  if (!target) {
    return toolError(
      base,
      req,
      block.id,
      send,
      'no target',
      'No database target is connected.'
    )
  }
  const input = (block.input ?? {}) as Record<string, unknown>
  // Force source: the agent only ever writes agent-sourced records. Strip any
  // caller-supplied source/timestamps; the store owns identity and stamping.
  const draft = { ...input, source: 'agent' } as KnowledgeRecordInput
  const kindLabel = typeof input.kind === 'string' ? input.kind : 'record'
  send({
    type: 'tool_start',
    chatId: req.chatId,
    toolId: block.id,
    name: block.name,
    sql: input.id ? `update knowledge ${kindLabel}` : `save knowledge ${kindLabel}`
  })
  const existed =
    typeof input.id === 'string' &&
    listRecords(target.connId, target.database).some((r) => r.id === input.id)
  let saved: KnowledgeRecord
  try {
    saved = saveRecord(target.connId, target.database, draft)
  } catch (err) {
    return toolError(
      base,
      req,
      block.id,
      send,
      'invalid record',
      `save_knowledge rejected the record: ${describeError(err)}`
    )
  }
  broadcastKnowledgeChanged(target.connId, target.database)
  // Flag (never block) refs the live schema cannot satisfy: the record is
  // saved either way — dangling refs are legal in the store — but the model
  // should fix a typo or lower the confidence rather than leave it silent.
  // Requires the introspection cached by this session's schema summary; when
  // absent, saving proceeds unchecked exactly as before.
  const keys = liveRefKeys(target)
  const unresolved = keys
    ? [
        ...new Set(
          knowledgeRefs(saved)
            .map((ref) => normalizeColumnKey(ref))
            .filter((key) => !keys.has(key))
        )
      ]
    : []
  send({
    type: 'tool_result',
    chatId: req.chatId,
    toolId: block.id,
    ok: true,
    summary: `${existed ? 'updated' : 'saved'} ${saved.kind}${unresolved.length > 0 ? ` (${unresolved.length} unresolved ref${unresolved.length === 1 ? '' : 's'})` : ''}`
  })
  return {
    ...base,
    content: JSON.stringify({
      id: saved.id,
      kind: saved.kind,
      action: existed ? 'updated' : 'created',
      unresolvedRefs: unresolved.length > 0 ? unresolved : undefined,
      note:
        unresolved.length > 0
          ? 'These references match nothing in the live schema. If they are typos, update the record (pass this id); if the schema is simply ahead/behind the code, lower the confidence.'
          : undefined
    })
  }
}

function execWriteEditor(
  req: AgentSendRequest,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Anthropic.ToolResultBlockParam {
  const sql = String((block.input as { sql?: unknown }).sql ?? '').trim()
  const base: Anthropic.ToolResultBlockParam = {
    type: 'tool_result',
    tool_use_id: block.id,
    content: ''
  }
  if (!sql) {
    return { ...base, content: 'No SQL provided.', is_error: true }
  }
  send({
    type: 'tool_start',
    chatId: req.chatId,
    toolId: block.id,
    name: block.name,
    sql
  })
  send({ type: 'editor_insert', chatId: req.chatId, sql })
  send({
    type: 'tool_result',
    chatId: req.chatId,
    toolId: block.id,
    ok: true,
    summary: 'written to editor'
  })
  return { ...base, content: 'The SQL was inserted into the active editor.' }
}

/**
 * Trim a list of result lines to the shared tool-result budget, reporting how
 * many were dropped so the model knows to narrow its query.
 */
function capLines(lines: string[], budget: number): { kept: string[]; dropped: number } {
  let used = 0
  let end = lines.length
  for (let i = 0; i < lines.length; i++) {
    used += lines[i].length + 1
    if (used > budget) {
      end = i
      break
    }
  }
  return { kept: lines.slice(0, end), dropped: lines.length - end }
}

/**
 * Shared shell for the three repo tools: emits tool_start with a readable
 * label, runs the primitive, converts thrown sandbox/filesystem errors into
 * ordinary tool errors, and reports a one-line summary. Repo primitives throw
 * user-readable messages by design, so those are forwarded verbatim.
 */
async function execRepoTool(
  req: AgentSendRequest,
  block: Anthropic.ToolUseBlock,
  send: Sender,
  label: string,
  run: () => Promise<{ content: string; summary: string }>
): Promise<Anthropic.ToolResultBlockParam> {
  const base: Anthropic.ToolResultBlockParam = {
    type: 'tool_result',
    tool_use_id: block.id,
    content: ''
  }
  send({
    type: 'tool_start',
    chatId: req.chatId,
    toolId: block.id,
    name: block.name,
    sql: label
  })
  try {
    const { content, summary } = await run()
    send({
      type: 'tool_result',
      chatId: req.chatId,
      toolId: block.id,
      ok: true,
      summary
    })
    return { ...base, content }
  } catch (err) {
    return toolError(base, req, block.id, send, 'failed', describeError(err))
  }
}

function execListRepoFiles(
  req: AgentSendRequest,
  root: string,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Promise<Anthropic.ToolResultBlockParam> {
  const input = (block.input ?? {}) as { dir?: unknown; glob?: unknown }
  const dir = typeof input.dir === 'string' ? input.dir : undefined
  const glob = typeof input.glob === 'string' ? input.glob : undefined
  const label = `repo: list ${[dir, glob].filter(Boolean).join(' ') || '(all)'}`
  return execRepoTool(req, block, send, label, async () => {
    const res = await listRepoFiles(root, dir, glob)
    const { kept, dropped } = capLines(res.files, TOOL_RESULT_MAX_CHARS - 200)
    const truncated = res.truncated || dropped > 0
    return {
      content: JSON.stringify({
        files: kept,
        note: truncated
          ? `truncated — ${kept.length} paths shown; narrow with dir or glob`
          : undefined
      }),
      summary: `${kept.length} file${kept.length === 1 ? '' : 's'}${truncated ? ' (truncated)' : ''}`
    }
  })
}

function execGrepRepo(
  req: AgentSendRequest,
  root: string,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Promise<Anthropic.ToolResultBlockParam> {
  const input = (block.input ?? {}) as {
    pattern?: unknown
    dir?: unknown
    glob?: unknown
    caseSensitive?: unknown
  }
  const pattern = String(input.pattern ?? '')
  const dir = typeof input.dir === 'string' ? input.dir : undefined
  const glob = typeof input.glob === 'string' ? input.glob : undefined
  const label = `repo: grep /${pattern}/${glob ? ` in ${glob}` : dir ? ` in ${dir}` : ''}`
  return execRepoTool(req, block, send, label, async () => {
    const res = await grepRepo(root, pattern, {
      dir,
      glob,
      caseSensitive: input.caseSensitive === true
    })
    const lines = res.matches.map((m) => `${m.path}:${m.line}: ${m.text}`)
    const { kept, dropped } = capLines(lines, TOOL_RESULT_MAX_CHARS - 200)
    const truncated = res.truncated || dropped > 0
    return {
      content: JSON.stringify({
        matches: kept,
        filesScanned: res.filesScanned,
        note: truncated
          ? `truncated — ${kept.length} matches shown; narrow the pattern, dir, or glob`
          : undefined
      }),
      summary: `${kept.length} match${kept.length === 1 ? '' : 'es'}${truncated ? ' (truncated)' : ''}`
    }
  })
}

function execReadRepoFile(
  req: AgentSendRequest,
  root: string,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Promise<Anthropic.ToolResultBlockParam> {
  const input = (block.input ?? {}) as {
    path?: unknown
    offset?: unknown
    limit?: unknown
  }
  const path = String(input.path ?? '')
  const label = `repo: read ${path}`
  return execRepoTool(req, block, send, label, async () => {
    const res = await readRepoFile(
      root,
      path,
      typeof input.offset === 'number' ? input.offset : undefined,
      typeof input.limit === 'number' ? input.limit : undefined
    )
    return {
      content: JSON.stringify({
        path: res.path,
        startLine: res.startLine,
        totalLines: res.totalLines,
        content: res.content,
        note: res.truncated
          ? 'truncated — use offset/limit to read further'
          : undefined
      }),
      summary: `${res.totalLines.toLocaleString()} line${res.totalLines === 1 ? '' : 's'}${res.truncated ? ' (partial)' : ''}`
    }
  })
}

async function execMcpTool(
  req: AgentSendRequest,
  tool: McpAgentTool,
  block: Anthropic.ToolUseBlock,
  send: Sender
): Promise<Anthropic.ToolResultBlockParam> {
  const base: Anthropic.ToolResultBlockParam = {
    type: 'tool_result',
    tool_use_id: block.id,
    content: ''
  }
  const input = (block.input ?? {}) as Record<string, unknown>
  const argsPreview = JSON.stringify(input)
  send({
    type: 'tool_start',
    chatId: req.chatId,
    toolId: block.id,
    name: block.name,
    sql: `${tool.serverName}: ${tool.toolName} ${argsPreview === '{}' ? '' : argsPreview}`.trim()
  })
  const res = await callMcpTool(tool.serverId, tool.toolName, input)
  const content =
    res.text.length > TOOL_RESULT_MAX_CHARS
      ? `${res.text.slice(0, TOOL_RESULT_MAX_CHARS)}\n…(truncated at ${TOOL_RESULT_MAX_CHARS} chars)`
      : res.text
  if (!res.ok) {
    return toolError(base, req, block.id, send, 'failed', content)
  }
  send({
    type: 'tool_result',
    chatId: req.chatId,
    toolId: block.id,
    ok: true,
    summary: `${res.text.length.toLocaleString()} chars`
  })
  return { ...base, content }
}

/**
 * Move the incremental cache breakpoint to the last (user) message so each
 * request reuses the previous request's cached prefix instead of paying for
 * the whole conversation again on every tool round-trip.
 */
function setCacheBreakpoint(messages: Anthropic.MessageParam[]): void {
  for (const msg of messages) {
    if (Array.isArray(msg.content)) {
      for (const blk of msg.content) {
        delete (blk as { cache_control?: unknown }).cache_control
      }
    }
  }
  const last = messages[messages.length - 1]
  if (!last) return
  if (typeof last.content === 'string') {
    last.content = [{ type: 'text', text: last.content }]
  }
  const tail = last.content[last.content.length - 1]
  if (tail) {
    ;(tail as { cache_control?: unknown }).cache_control = { type: 'ephemeral' }
  }
}

/**
 * An errored or aborted turn can leave the history ending in an assistant
 * message with unanswered tool_use blocks, which the API rejects on every
 * later request — the chat would be wedged for good. Pair each dangling
 * tool_use with a synthetic error result before starting the next turn.
 */
function repairDanglingToolUses(messages: Anthropic.MessageParam[]): void {
  const last = messages[messages.length - 1]
  if (!last || last.role !== 'assistant' || !Array.isArray(last.content)) return
  const results: Anthropic.ToolResultBlockParam[] = []
  for (const blk of last.content) {
    if (blk.type === 'tool_use') {
      results.push({
        type: 'tool_result',
        tool_use_id: blk.id,
        content: 'Interrupted before the tool ran.',
        is_error: true
      })
    }
  }
  if (results.length > 0) messages.push({ role: 'user', content: results })
}

/** Human-readable message for a failed request (the raw body is JSON noise). */
function describeError(err: unknown): string {
  if (err instanceof Anthropic.APIError) {
    const body = err.error as { error?: { message?: string } } | null | undefined
    const detail = body?.error?.message
    if (detail) {
      return err.status ? `API error ${err.status}: ${detail}` : detail
    }
    return `${err.status ?? ''} ${err.message}`.trim()
  }
  return err instanceof Error ? err.message : String(err)
}

async function runAgentTurn(
  req: AgentSendRequest,
  send: Sender
): Promise<void> {
  const { key } = loadKey()
  if (!key) {
    send({
      type: 'error',
      chatId: req.chatId,
      message: `No API key found. Add \`export ${API_KEY_VAR}=...\` to ~/.zshrc and try again.`
    })
    return
  }
  const model = AGENT_MODELS.find((m) => m.id === req.model) ?? AGENT_MODELS[0]
  const chat = getChat(req.chatId)
  if (chat.controller) {
    send({
      type: 'error',
      chatId: req.chatId,
      message: 'A response is already in progress.'
    })
    return
  }
  const controller = new AbortController()
  chat.controller = controller

  // Fail closed: a renderer bug or tampering that sends 'write-admin' or
  // garbage silently degrades to Metadata Only.
  const mode = resolveAgentMode(req.mode)
  const client = new Anthropic({ apiKey: key })
  // Dialect follows the target connection's engine; chats without a target
  // default to PostgreSQL guidance.
  const dialect = dialectFor(
    req.target ? getConnectionType(req.target.connId) : null
  )
  const schemaSummary = req.target ? await schemaSummaryFor(req.target) : null
  // MCP tools are user-configured and mode-independent: the access mode
  // protects the connected database, while MCP servers act on external
  // systems with their own credentials. Snapshot once per turn so the tool
  // array and the dispatch below cannot disagree mid-turn.
  const mcpTools = mcpToolsForTurn()
  const mcpByName = new Map(mcpTools.map((t) => [t.namespacedName, t]))
  // Repo access requires both halves: the renderer's per-chat toggle AND a
  // main-side configured root for the target connection. The request never
  // carries a path, so a tampered renderer can at most toggle access to the
  // directory the user already attached through the main-process picker.
  const repoRoot =
    req.repo && req.target ? getRepoRoot(req.target.connId) : null
  const repo: RepoPromptInfo | null = repoRoot
    ? { root: repoRoot, commit: await getRepoCommit(repoRoot) }
    : null
  // The system prompt (with the schema summary) is by far the largest stable
  // prefix; cache it so follow-up turns and tool round-trips reuse it.
  const system: Anthropic.TextBlockParam[] = [
    {
      type: 'text',
      text: buildSystemPrompt(req, mode, schemaSummary, dialect, mcpTools, repo),
      cache_control: { type: 'ephemeral' }
    }
  ]
  // Metadata Only offers no execution tools at all (Layer 1); its schema
  // knowledge is the system-prompt summary above.
  const tools: Anthropic.Messages.ToolUnion[] =
    req.target && mode === 'read-only'
      ? [
          WRITE_EDITOR_TOOL,
          runSqlTool(dialect),
          explainQueryTool(dialect),
          describeTableTool(dialect),
          searchSchemaTool(dialect)
        ]
      : [WRITE_EDITOR_TOOL]
  // search_knowledge and save_knowledge read/write only the local knowledge
  // store — never the warehouse — so both are offered in Metadata Only as well
  // as Read-Only. They require a target because records are keyed to it.
  if (req.target) tools.push(SEARCH_KNOWLEDGE_TOOL, SAVE_KNOWLEDGE_TOOL)
  // Repo tools read only the attached local checkout — never the database —
  // so, like the knowledge tools, they are mode-independent.
  if (repoRoot) {
    tools.push(LIST_REPO_FILES_TOOL, GREP_REPO_TOOL, READ_REPO_FILE_TOOL)
  }
  for (const t of mcpTools) {
    tools.push({
      name: t.namespacedName,
      description: `Tool "${t.toolName}" from the user-configured MCP server "${t.serverName}".${t.description ? ` ${t.description}` : ''}`,
      input_schema: t.inputSchema as Anthropic.Tool.InputSchema
    })
  }
  // Web search runs server-side; results come back as content blocks, so
  // there is no execution branch in the tool-use loop below.
  const webTool = req.webSearch ? webSearchTool(model.id) : null
  if (webTool) tools.push(webTool)
  // The dynamic-filtering variant runs code execution in a server-side
  // container; its id must be echoed back on requests that continue the
  // conversation, and it may only be sent when the tool is in the request.
  const canSendContainer = webTool?.type === 'web_search_20260209'

  repairDanglingToolUses(chat.messages)
  chat.messages.push({ role: 'user', content: req.prompt })

  // Latest known context occupancy, updated after every API call so the
  // renderer's gauge stays accurate even when the turn aborts mid-loop.
  let contextTokens: number | null = null

  try {
    for (;;) {
      setCacheBreakpoint(chat.messages)
      // Reuse the live container, dropping it shortly before it expires so a
      // stale id doesn't fail the request.
      const containerId =
        canSendContainer &&
        chat.container &&
        Date.parse(chat.container.expiresAt) - Date.now() > 30_000
          ? chat.container.id
          : null
      const stream = client.messages.stream(
        {
          model: model.id,
          max_tokens: 64_000,
          ...(containerId ? { container: containerId } : {}),
          ...(model.adaptiveThinking ? { thinking: { type: 'adaptive' } } : {}),
          ...(req.effort && model.efforts.includes(req.effort)
            ? { output_config: { effort: req.effort } }
            : {}),
          system,
          tools,
          messages: chat.messages
        },
        { signal: controller.signal }
      )

      stream.on('text', (delta) => {
        send({ type: 'text_delta', chatId: req.chatId, text: delta })
      })
      stream.on('contentBlock', (block) => {
        if (block.type === 'thinking') {
          send({ type: 'thinking', chatId: req.chatId, active: false })
        }
        // Web search executes server-side mid-stream; mirror it into the
        // transcript the same way client tools are shown.
        if (block.type === 'server_tool_use' && block.name === 'web_search') {
          const query = String(
            (block.input as { query?: unknown })?.query ?? ''
          )
          send({
            type: 'tool_start',
            chatId: req.chatId,
            toolId: block.id,
            name: block.name,
            sql: `web search "${query}"`
          })
        }
        if (block.type === 'web_search_tool_result') {
          const content = block.content
          send(
            Array.isArray(content)
              ? {
                  type: 'tool_result',
                  chatId: req.chatId,
                  toolId: block.tool_use_id,
                  ok: true,
                  summary: `${content.length} result${content.length === 1 ? '' : 's'}`
                }
              : {
                  type: 'tool_result',
                  chatId: req.chatId,
                  toolId: block.tool_use_id,
                  ok: false,
                  summary: `search failed: ${content.error_code}`
                }
          )
        }
      })
      stream.on('streamEvent', (evt) => {
        if (
          evt.type === 'content_block_start' &&
          evt.content_block.type === 'thinking'
        ) {
          send({ type: 'thinking', chatId: req.chatId, active: true })
        }
      })

      const message = await stream.finalMessage()
      const usage = message.usage
      contextTokens =
        usage.input_tokens +
        (usage.cache_read_input_tokens ?? 0) +
        (usage.cache_creation_input_tokens ?? 0) +
        usage.output_tokens
      chat.messages.push({ role: 'assistant', content: message.content })
      if (message.container) {
        chat.container = {
          id: message.container.id,
          expiresAt: message.container.expires_at
        }
      }

      if (message.stop_reason === 'pause_turn') continue

      if (message.stop_reason === 'tool_use') {
        const toolUses = message.content.filter(
          (b): b is Anthropic.ToolUseBlock => b.type === 'tool_use'
        )
        const results: Anthropic.ToolResultBlockParam[] = []
        for (const block of toolUses) {
          if (block.name === 'run_sql') {
            results.push(await execRunSql(req, chat, mode, block, send))
          } else if (block.name === 'explain_query') {
            results.push(
              await execExplain(req, chat, mode, block, send, dialect)
            )
          } else if (block.name === 'describe_table') {
            results.push(await execDescribeTable(req, mode, block, send))
          } else if (block.name === 'search_schema') {
            results.push(await execSearchSchema(req, mode, block, send))
          } else if (block.name === 'search_knowledge') {
            results.push(execSearchKnowledge(req, block, send))
          } else if (block.name === 'save_knowledge') {
            results.push(execSaveKnowledge(req, block, send))
          } else if (block.name === 'write_to_editor') {
            results.push(execWriteEditor(req, block, send))
          } else if (repoRoot && block.name === 'list_repo_files') {
            results.push(await execListRepoFiles(req, repoRoot, block, send))
          } else if (repoRoot && block.name === 'grep_repo') {
            results.push(await execGrepRepo(req, repoRoot, block, send))
          } else if (repoRoot && block.name === 'read_repo_file') {
            results.push(await execReadRepoFile(req, repoRoot, block, send))
          } else if (mcpByName.has(block.name)) {
            const tool = mcpByName.get(block.name) as McpAgentTool
            results.push(await execMcpTool(req, tool, block, send))
          } else {
            results.push({
              type: 'tool_result',
              tool_use_id: block.id,
              content: `Unknown tool: ${block.name}`,
              is_error: true
            })
          }
        }
        chat.messages.push({ role: 'user', content: results })
        continue
      }

      send({
        type: 'done',
        chatId: req.chatId,
        stopReason: message.stop_reason,
        contextTokens
      })
      return
    }
  } catch (err) {
    if (
      err instanceof Anthropic.APIUserAbortError ||
      controller.signal.aborted
    ) {
      send({
        type: 'done',
        chatId: req.chatId,
        stopReason: 'aborted',
        contextTokens
      })
      return
    }
    send({ type: 'error', chatId: req.chatId, message: describeError(err) })
  } finally {
    chat.controller = null
  }
}

/** Cap on the summary a /compact call may produce. */
const COMPACT_MAX_TOKENS = 8192

const COMPACT_PROMPT = [
  'Summarize this conversation so the summary can replace the full history as context for future turns.',
  "Preserve, concisely: the user's goals and open questions; every schema fact learned (tables, columns, types, keys); key findings from queries that were run; the latest SQL under discussion, verbatim if it was final; and any constraints or preferences the user stated.",
  'Omit pleasantries and dead ends. Respond with the summary only.'
].join(' ')

/** Replace the chat history with a model-written summary of it (/compact). */
async function compactChat(
  chatId: string,
  modelId: string
): Promise<AgentCompactResult> {
  const { key } = loadKey()
  if (!key) {
    return {
      ok: false,
      error: `No API key found. Add \`export ${API_KEY_VAR}=...\` to ~/.zshrc and try again.`
    }
  }
  const chat = chats.get(chatId)
  if (!chat || chat.messages.length === 0) {
    return { ok: false, error: 'Nothing to compact — the conversation is empty.' }
  }
  if (chat.controller) {
    return {
      ok: false,
      error: 'Wait for the current response to finish before compacting.'
    }
  }
  const model = AGENT_MODELS.find((m) => m.id === modelId) ?? AGENT_MODELS[0]
  const client = new Anthropic({ apiKey: key })

  // An aborted turn can leave dangling tool_use blocks; pair each with a
  // synthetic result or the API rejects the transcript.
  const content: Anthropic.ContentBlockParam[] = []
  const last = chat.messages[chat.messages.length - 1]
  if (last?.role === 'assistant' && Array.isArray(last.content)) {
    for (const blk of last.content) {
      if (blk.type === 'tool_use') {
        content.push({
          type: 'tool_result',
          tool_use_id: blk.id,
          content: 'Interrupted before the tool ran.',
          is_error: true
        })
      }
    }
  }
  content.push({ type: 'text', text: COMPACT_PROMPT })

  try {
    const resp = await client.messages.create({
      model: model.id,
      max_tokens: COMPACT_MAX_TOKENS,
      messages: [...chat.messages, { role: 'user', content }]
    })
    const summary = resp.content
      .filter((b): b is Anthropic.TextBlock => b.type === 'text')
      .map((b) => b.text)
      .join('\n')
      .trim()
    if (!summary) {
      return {
        ok: false,
        error: 'Compaction failed: the model returned no summary.'
      }
    }
    // Replace the history with a user/assistant pair so the next turn still
    // alternates roles cleanly.
    chat.messages.length = 0
    chat.messages.push(
      {
        role: 'user',
        content: `The earlier conversation was compacted to save context. Summary of everything so far:\n\n${summary}`
      },
      {
        role: 'assistant',
        content: 'Understood — continuing from that summary.'
      }
    )
    // The summary's output tokens approximate the new occupancy; the gauge
    // self-corrects with exact numbers on the next turn.
    return { ok: true, contextTokens: resp.usage.output_tokens }
  } catch (err) {
    return { ok: false, error: `Compaction failed: ${describeError(err)}` }
  }
}

/** Abort the stream and cancel the running statement. */
function stopChat(chatId: string): void {
  const chat = chats.get(chatId)
  if (!chat) return
  chat.controller?.abort()
  const cancel = chat.cancelRunningQuery
  if (cancel) {
    chat.cancelRunningQuery = null
    cancel()
  }
}

export function registerAgentHandlers(
  getWindow: () => BrowserWindow | null
): void {
  const send: Sender = (evt) => {
    const win = getWindow()
    if (win && !win.isDestroyed()) win.webContents.send('agent:event', evt)
  }
  // Mirror the UI save path's push so the save_knowledge tool refreshes any
  // open renderer knowledge views.
  broadcastKnowledgeChanged = (connId, database) => {
    const win = getWindow()
    if (win && !win.isDestroyed()) {
      win.webContents.send('knowledge:changed', { connId, database })
    }
  }

  ipcMain.handle('agent:keyStatus', (): AgentKeyStatus => {
    const { key, source } = loadKey()
    return { found: key !== null, source }
  })

  ipcMain.handle('agent:send', async (_event, req: AgentSendRequest) => {
    await runAgentTurn(req, send)
  })

  ipcMain.handle('agent:stop', (_event, chatId: string) => {
    stopChat(chatId)
  })

  ipcMain.handle(
    'agent:compact',
    (_event, chatId: string, model: string): Promise<AgentCompactResult> =>
      compactChat(chatId, model)
  )

  ipcMain.handle('agent:reset', (_event, chatId: string) => {
    stopChat(chatId)
    chats.delete(chatId)
    // Schema may have changed since it was cached; a fresh chat re-introspects.
    schemaCache.clear()
    introspectionCache.clear()
  })
}
