/**
 * PostgreSQL vocabulary offered by the completion provider alongside
 * schema-derived items. Curated for query editing, not an exhaustive
 * grammar: common statement, clause, and expression keywords.
 */

export const KEYWORDS = [
  'SELECT',
  'FROM',
  'WHERE',
  'JOIN',
  'INNER JOIN',
  'LEFT JOIN',
  'RIGHT JOIN',
  'FULL JOIN',
  'CROSS JOIN',
  'LATERAL',
  'ON',
  'USING',
  'GROUP BY',
  'ORDER BY',
  'HAVING',
  'LIMIT',
  'OFFSET',
  'DISTINCT',
  'DISTINCT ON',
  'AS',
  'ASC',
  'DESC',
  'NULLS FIRST',
  'NULLS LAST',
  'UNION',
  'UNION ALL',
  'INTERSECT',
  'EXCEPT',
  'WITH',
  'RECURSIVE',
  'INSERT INTO',
  'VALUES',
  'UPDATE',
  'SET',
  'DELETE FROM',
  'RETURNING',
  'ON CONFLICT',
  'DO NOTHING',
  'DO UPDATE SET',
  'MERGE INTO',
  'TRUNCATE',
  'CREATE TABLE',
  'CREATE INDEX',
  'CREATE VIEW',
  'CREATE MATERIALIZED VIEW',
  'CREATE SEQUENCE',
  'CREATE SCHEMA',
  'CREATE FUNCTION',
  'CREATE EXTENSION',
  'ALTER TABLE',
  'DROP TABLE',
  'DROP INDEX',
  'DROP VIEW',
  'ADD COLUMN',
  'DROP COLUMN',
  'RENAME TO',
  'IF EXISTS',
  'IF NOT EXISTS',
  'PRIMARY KEY',
  'FOREIGN KEY',
  'REFERENCES',
  'UNIQUE',
  'CHECK',
  'DEFAULT',
  'NOT NULL',
  'CONSTRAINT',
  'CASCADE',
  'RESTRICT',
  'AND',
  'OR',
  'NOT',
  'IN',
  'EXISTS',
  'BETWEEN',
  'LIKE',
  'ILIKE',
  'SIMILAR TO',
  'IS NULL',
  'IS NOT NULL',
  'IS DISTINCT FROM',
  'ANY',
  'ALL',
  'SOME',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'CAST',
  'ARRAY',
  'INTERVAL',
  'TRUE',
  'FALSE',
  'NULL',
  'CURRENT_DATE',
  'CURRENT_TIMESTAMP',
  'CURRENT_TIME',
  'CURRENT_USER',
  'SESSION_USER',
  'FETCH FIRST',
  'FOR UPDATE',
  'FOR SHARE',
  'TABLESAMPLE',
  'WINDOW',
  'PARTITION BY',
  'OVER',
  'FILTER',
  'WITHIN GROUP',
  'ROWS BETWEEN',
  'RANGE BETWEEN',
  'UNBOUNDED PRECEDING',
  'UNBOUNDED FOLLOWING',
  'CURRENT ROW',
  'GROUPING SETS',
  'ROLLUP',
  'CUBE',
  'BEGIN',
  'COMMIT',
  'ROLLBACK',
  'SAVEPOINT',
  'EXPLAIN',
  'EXPLAIN ANALYZE',
  'VACUUM',
  'ANALYZE',
  'GRANT',
  'REVOKE',
  'COMMENT ON',
  'SHOW',
  'SET LOCAL',
  'RESET'
]

/** Built-in functions worth offering without schema introspection. */
export const BUILTIN_FUNCTIONS = [
  'count',
  'sum',
  'avg',
  'min',
  'max',
  'coalesce',
  'nullif',
  'greatest',
  'least',
  'abs',
  'ceil',
  'floor',
  'round',
  'trunc',
  'power',
  'sqrt',
  'exp',
  'ln',
  'log',
  'mod',
  'sign',
  'width_bucket',
  'length',
  'char_length',
  'lower',
  'upper',
  'initcap',
  'trim',
  'ltrim',
  'rtrim',
  'lpad',
  'rpad',
  'substring',
  'substr',
  'replace',
  'reverse',
  'repeat',
  'left',
  'right',
  'position',
  'strpos',
  'split_part',
  'concat',
  'concat_ws',
  'format',
  'regexp_replace',
  'regexp_match',
  'regexp_matches',
  'regexp_split_to_table',
  'starts_with',
  'md5',
  'to_char',
  'to_date',
  'to_timestamp',
  'to_number',
  'age',
  'date_trunc',
  'date_part',
  'extract',
  'justify_interval',
  'make_date',
  'make_interval',
  'make_timestamp',
  'string_agg',
  'array_agg',
  'array_length',
  'array_to_string',
  'string_to_array',
  'unnest',
  'cardinality',
  'generate_series',
  'row_number',
  'rank',
  'dense_rank',
  'percent_rank',
  'ntile',
  'lag',
  'lead',
  'first_value',
  'last_value',
  'nth_value',
  'cume_dist',
  'json_agg',
  'jsonb_agg',
  'json_build_object',
  'jsonb_build_object',
  'json_array_elements',
  'jsonb_array_elements',
  'jsonb_object_keys',
  'jsonb_set',
  'jsonb_pretty',
  'to_json',
  'to_jsonb',
  'pg_typeof',
  'pg_size_pretty',
  'pg_total_relation_size',
  'nextval',
  'currval',
  'setval'
]

/** Built-in functions taking no arguments, completed as `fn()`. */
export const NO_ARG_FUNCTIONS = new Set([
  'now',
  'random',
  'gen_random_uuid',
  'clock_timestamp',
  'statement_timestamp',
  'transaction_timestamp',
  'txid_current',
  'pg_backend_pid',
  'version'
])

export const BUILTIN_TYPES = [
  'bigint',
  'bigserial',
  'bit',
  'boolean',
  'box',
  'bytea',
  'char',
  'character',
  'cidr',
  'circle',
  'date',
  'decimal',
  'double precision',
  'float4',
  'float8',
  'inet',
  'int',
  'int2',
  'int4',
  'int8',
  'integer',
  'interval',
  'json',
  'jsonb',
  'line',
  'lseg',
  'macaddr',
  'money',
  'numeric',
  'path',
  'point',
  'polygon',
  'real',
  'serial',
  'smallint',
  'smallserial',
  'text',
  'time',
  'timestamp',
  'timestamptz',
  'timetz',
  'tsquery',
  'tsvector',
  'uuid',
  'varchar',
  'xml'
]

/**
 * Everyday query keywords, in rough frequency-of-use order. The completion
 * provider ranks these ahead of the rest of KEYWORDS so that e.g. typing
 * "wh" offers WHERE before WHEN. Must stay a subset of KEYWORDS.
 */
export const COMMON_KEYWORDS = [
  'SELECT',
  'FROM',
  'WHERE',
  'JOIN',
  'LEFT JOIN',
  'GROUP BY',
  'ORDER BY',
  'LIMIT',
  'AND',
  'OR',
  'ON',
  'AS',
  'INNER JOIN',
  'HAVING',
  'DISTINCT',
  'CASE',
  'WITH',
  'UNION ALL',
  'INSERT INTO',
  'UPDATE',
  'SET',
  'DELETE FROM',
  'DESC',
  'ASC',
  'IN',
  'NOT',
  'IS NULL',
  'IS NOT NULL',
  'BETWEEN',
  'LIKE',
  'ILIKE',
  'EXISTS',
  'OFFSET'
]

export const COMMON_KEYWORD_RANK = new Map(COMMON_KEYWORDS.map((kw, i) => [kw, i]))

const KEYWORD_WORDS = new Set(KEYWORDS.flatMap((kw) => kw.toLowerCase().split(' ')))

/** True when `name` needs double quotes to be used as an identifier. */
export function needsQuoting(name: string): boolean {
  return !/^[a-z_][a-z0-9_$]*$/.test(name) || KEYWORD_WORDS.has(name)
}

export function quoteIdent(name: string): string {
  return needsQuoting(name) ? `"${name.replace(/"/g, '""')}"` : name
}
